/*
 * ConfiguracionMatcher.java
 *
 * Created on 4 de julio de 2008, 02:23 PM
 */

package sconnectmail;

import BD.DesEncrypter;
import BD.ManejadorBD;
import Objetos.Cliente;
import java.util.List;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import org.openswing.swing.client.OptionPane;


/**
 *
 * @author  pbcgvb
 */
public class Clientes extends javax.swing.JPanel {
    
    /** Creates new form ConfiguracionMatcher */
    public Clientes(){ 
     
        initComponents();
        ParametrosGenerales.setVisible(true); 
        ParametrosGenerales1.setVisible(true);
        
//        mostrarCliente(0);
//        ClientesTable.setColumnSelectionInterval(0,1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Explorador = new javax.swing.JFrame();
        FileChooser = new javax.swing.JFileChooser();
        ParametrosGenerales = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        ContenedorClientes = new javax.swing.JScrollPane();
        ClientesTable = new javax.swing.JTable();
        Agregar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        ParametrosGenerales1 = new javax.swing.JPanel();
        Titulo1 = new javax.swing.JLabel();
        PanelDetalles = new javax.swing.JPanel();
        LabelCorreo = new javax.swing.JLabel();
        Correo = new javax.swing.JFormattedTextField();
        Cliente = new javax.swing.JTextField();
        LabelCliente = new javax.swing.JLabel();
        Aceptar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        Explorador.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sconnectmail.SconnectMailApp.class).getContext().getResourceMap(Clientes.class);
        Explorador.setTitle(resourceMap.getString("Explorador.title")); // NOI18N
        Explorador.setName("Explorador"); // NOI18N

        FileChooser.setDialogTitle(resourceMap.getString("FileChooser.dialogTitle")); // NOI18N
        FileChooser.setName("FileChooser"); // NOI18N

        javax.swing.GroupLayout ExploradorLayout = new javax.swing.GroupLayout(Explorador.getContentPane());
        Explorador.getContentPane().setLayout(ExploradorLayout);
        ExploradorLayout.setHorizontalGroup(
            ExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
            .addGroup(ExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExploradorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ExploradorLayout.setVerticalGroup(
            ExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
            .addGroup(ExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExploradorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setMaximumSize(new java.awt.Dimension(837, 640));
        setMinimumSize(new java.awt.Dimension(837, 640));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(837, 640));

        ParametrosGenerales.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ParametrosGenerales.setMaximumSize(new java.awt.Dimension(443, 430));
        ParametrosGenerales.setMinimumSize(new java.awt.Dimension(805, 430));
        ParametrosGenerales.setName("ParametrosGenerales"); // NOI18N
        ParametrosGenerales.setPreferredSize(new java.awt.Dimension(805, 430));
        ParametrosGenerales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(resourceMap.getColor("Titulo.background")); // NOI18N
        Titulo.setFont(resourceMap.getFont("Titulo.font")); // NOI18N
        Titulo.setForeground(resourceMap.getColor("Titulo.foreground")); // NOI18N
        Titulo.setText(resourceMap.getString("Titulo.text")); // NOI18N
        Titulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Titulo.setMaximumSize(new java.awt.Dimension(800, 28));
        Titulo.setMinimumSize(new java.awt.Dimension(800, 28));
        Titulo.setName("Titulo"); // NOI18N
        Titulo.setOpaque(true);
        Titulo.setPreferredSize(new java.awt.Dimension(800, 28));
        ParametrosGenerales.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, -1));

        ContenedorClientes.setName("ContenedorClientes"); // NOI18N

        ClientesTable.setAutoCreateRowSorter(true);
        ClientesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ClientesTable.setName("ClientesTable"); // NOI18N
        org.jdesktop.beansbinding.BindingGroup bindingGroup;
        java.util.List<Objetos.Cliente> clienteList;
        javax.persistence.Query clienteQuery;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();
        javax.persistence.EntityManager AlertasSwiftPUEntityManager;
        AlertasSwiftPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("AlertasSwiftPU").createEntityManager();
        clienteQuery = java.beans.Beans.isDesignTime() ? null : AlertasSwiftPUEntityManager.createQuery("SELECT c FROM Cliente c");

        clienteList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : clienteQuery.getResultList();
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, clienteList, ClientesTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombre}"));
        columnBinding.setColumnName("Código Cliente");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${mail}"));
        columnBinding.setColumnName("Correo");
        columnBinding.setColumnClass(String.class);
        jTableBinding.bind();
        try{ClientesTable.addRowSelectionInterval(0,0);}catch(Exception e){}
        ClientesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientesTableMouseClicked(evt);
            }
        });
        ClientesTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ClientesTableKeyReleased(evt);
            }
        });
        ContenedorClientes.setViewportView(ClientesTable);

        ParametrosGenerales.add(ContenedorClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 640, 255));

        Agregar.setText(resourceMap.getString("Agregar.text")); // NOI18N
        Agregar.setMaximumSize(new java.awt.Dimension(81, 23));
        Agregar.setMinimumSize(new java.awt.Dimension(81, 23));
        Agregar.setName("Agregar"); // NOI18N
        Agregar.setPreferredSize(new java.awt.Dimension(81, 23));
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        ParametrosGenerales.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 81, 23));

        Eliminar.setText(resourceMap.getString("Eliminar.text")); // NOI18N
        Eliminar.setMaximumSize(new java.awt.Dimension(81, 23));
        Eliminar.setMinimumSize(new java.awt.Dimension(81, 23));
        Eliminar.setName("Eliminar"); // NOI18N
        Eliminar.setPreferredSize(new java.awt.Dimension(81, 23));
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        ParametrosGenerales.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 81, 23));

        ParametrosGenerales1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ParametrosGenerales1.setMaximumSize(new java.awt.Dimension(443, 430));
        ParametrosGenerales1.setMinimumSize(new java.awt.Dimension(805, 430));
        ParametrosGenerales1.setName("ParametrosGenerales1"); // NOI18N
        ParametrosGenerales1.setPreferredSize(new java.awt.Dimension(805, 430));
        ParametrosGenerales1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo1.setBackground(resourceMap.getColor("Titulo1.background")); // NOI18N
        Titulo1.setFont(resourceMap.getFont("Titulo1.font")); // NOI18N
        Titulo1.setForeground(resourceMap.getColor("Titulo1.foreground")); // NOI18N
        Titulo1.setText(resourceMap.getString("Titulo1.text")); // NOI18N
        Titulo1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Titulo1.setMaximumSize(new java.awt.Dimension(800, 28));
        Titulo1.setMinimumSize(new java.awt.Dimension(800, 28));
        Titulo1.setName("Titulo1"); // NOI18N
        Titulo1.setOpaque(true);
        Titulo1.setPreferredSize(new java.awt.Dimension(800, 28));
        ParametrosGenerales1.add(Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, -1));

        PanelDetalles.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelDetalles.setName("PanelDetalles"); // NOI18N

        LabelCorreo.setText(resourceMap.getString("LabelCorreo.text")); // NOI18N
        LabelCorreo.setName("LabelCorreo"); // NOI18N

        Correo.setName("Correo"); // NOI18N

        Cliente.setName("Cliente"); // NOI18N

        LabelCliente.setText(resourceMap.getString("LabelCliente.text")); // NOI18N
        LabelCliente.setName("LabelCliente"); // NOI18N

        javax.swing.GroupLayout PanelDetallesLayout = new javax.swing.GroupLayout(PanelDetalles);
        PanelDetalles.setLayout(PanelDetallesLayout);
        PanelDetallesLayout.setHorizontalGroup(
            PanelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetallesLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addGroup(PanelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelCliente)
                    .addComponent(LabelCorreo))
                .addGap(18, 18, 18)
                .addGroup(PanelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Correo)
                    .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        PanelDetallesLayout.setVerticalGroup(
            PanelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetallesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(PanelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCliente)
                    .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(PanelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        ParametrosGenerales1.add(PanelDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 780, 160));

        Aceptar.setText(resourceMap.getString("Aceptar.text")); // NOI18N
        Aceptar.setMaximumSize(new java.awt.Dimension(81, 23));
        Aceptar.setMinimumSize(new java.awt.Dimension(81, 23));
        Aceptar.setName("Aceptar"); // NOI18N
        Aceptar.setPreferredSize(new java.awt.Dimension(81, 23));
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        ParametrosGenerales1.add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 81, 23));

        Cancelar.setText(resourceMap.getString("Cancelar.text")); // NOI18N
        Cancelar.setMaximumSize(new java.awt.Dimension(81, 23));
        Cancelar.setMinimumSize(new java.awt.Dimension(81, 23));
        Cancelar.setName("Cancelar"); // NOI18N
        Cancelar.setPreferredSize(new java.awt.Dimension(81, 23));
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        ParametrosGenerales1.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 81, 23));

        jSeparator1.setName("jSeparator1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ParametrosGenerales1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ParametrosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ParametrosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(ParametrosGenerales1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

 
private void ClientesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientesTableMouseClicked
    try{
        Cliente.setText((String) ClientesTable.getValueAt(ClientesTable.getSelectedRow(), 0));
        Correo.setText((String) ClientesTable.getValueAt(ClientesTable.getSelectedRow(), 1));        
    }catch(Exception e){}
}//GEN-LAST:event_ClientesTableMouseClicked

private void ClientesTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClientesTableKeyReleased

//        cambioMoneda();
}//GEN-LAST:event_ClientesTableKeyReleased

private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        if(paramVacios()){OptionPane.showMessageDialog(null,"Debe completar todos los campos","Error",JOptionPane.ERROR_MESSAGE); }
        else{
        int opcion = OptionPane.showConfirmDialog(null,"¿Está seguro que desea modificar el registro?","Advertencia",JOptionPane.YES_NO_OPTION);  //0 Aceptar

        if (opcion == 0){       
       
            Vector datos = new Vector();
            
            datos.add(Cliente.getText());
            datos.add(Correo.getText());
            
            if(agregar){
                datos.add("");
            }
            else{
                datos.add(ClientesTable.getValueAt(ClientesTable.getSelectedRow(), 0).toString());
            }           
           
            ManejadorBD.setCliente(datos);
            ManejadorBD.updateClientes(ClientesTable);
            agregar = false;
        }
        }
}//GEN-LAST:event_AceptarActionPerformed

private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
       
}//GEN-LAST:event_CancelarActionPerformed

private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
    Cliente.setText("");
    Correo.setText("");
    agregar = true;
}//GEN-LAST:event_AgregarActionPerformed

private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
 int opcion = OptionPane.showConfirmDialog(null,"Está seguro que desea eliminar el registro?","Advertencia",JOptionPane.WARNING_MESSAGE);  //0 Aceptar 
    
    if(opcion == 0){
        String codigoCliente = (String) ClientesTable.getValueAt(ClientesTable.getSelectedRow(), 0);
        ManejadorBD.deleteCliente(codigoCliente);
        Cliente.setText("");
        Correo.setText("");
        agregar = true;
        ManejadorBD.updateClientes(ClientesTable);
    }
}//GEN-LAST:event_EliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField Cliente;
    private javax.swing.JTable ClientesTable;
    private javax.swing.JScrollPane ContenedorClientes;
    private javax.swing.JFormattedTextField Correo;
    private javax.swing.JButton Eliminar;
    private javax.swing.JFrame Explorador;
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JLabel LabelCliente;
    private javax.swing.JLabel LabelCorreo;
    private javax.swing.JPanel PanelDetalles;
    private javax.swing.JPanel ParametrosGenerales;
    private javax.swing.JPanel ParametrosGenerales1;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

   private boolean agregar = true; 
   DefaultTableModel modelo = new DefaultTableModel();
    
   public boolean paramVacios(){
        if(Cliente.getText().isEmpty() && Correo.getText().isEmpty()){return true;}
        else{return false;}
   }
   
//   public void listarClientes(){
//        modelo.setRowCount(0);
//        List clientes = ManejadorBD.getClientes();
//  
//        for (int i = 0; i < clientes.size(); i++) {
//            Cliente cliente = (Cliente) clientes.get(i);
//            Vector aux = new Vector();
//            
//            aux.add(cliente.getNombre());
//            aux.add(cliente.getMail());
//          
//
//            modelo.addRow(aux);            
//        }
//    }
   
//   public void mostrarCliente(int fila){
//        
//        if(ClientesTable.getRowCount() != 0){
//            resetCampos(1);
//            Cliente cliente = ManejadorBD.getClientes((BigDecimal) AlertasTable.getValueAt(fila,9));
//            
//            if(alerta.getMesgIo() != null){IOComboBoxDetalle.setSelectedItem(alerta.getMesgIo());}else{IOComboBoxDetalle.setSelectedIndex(0);}
//            MTDetalle.setText(alerta.getMesgMt());           
//            MonedaDetalle.setText(alerta.getMesgMoneda());
//            if(alerta.getMesgMonto() != null){MontoDetalle.setText(alerta.getMesgMonto().toString());}else{MontoDetalle.setText("");} 
//            CorreoDetalle.setText(alerta.getCorreo());            
//        }
//    }
    
}
