/*
 * SconnectMailView.java
 */

package sconnectmail;

import BD.ManejadorBD;
import Objetos.Regla;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import java.math.BigDecimal;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.openswing.swing.client.OptionPane;

/**
 * The application's main frame.
 */
public class SconnectMailView extends FrameView {

    public SconnectMailView(SingleFrameApplication app) {
        super(app);

        initComponents();
        
        Configuracion.setVisible(false);
        EmailClientes.setVisible(false);

       // listarAlertas();
      //  mostrarAlerta(0);
      //  AlertasTable.setColumnSelectionInterval(0,1);
    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sconnect_Mail = new javax.swing.JPanel();
        Navegador = new javax.swing.JPanel();
        EtiquetaPrincipal = new javax.swing.JLabel();
        BotonReglas = new javax.swing.JButton();
        EtiquetaReglas = new javax.swing.JLabel();
        BotonConfiguracion = new javax.swing.JButton();
        EtiquetaConfig = new javax.swing.JLabel();
        BotonEmailClientes = new javax.swing.JButton();
        EtiquetaEmail = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();
        CapasContenido = new javax.swing.JLayeredPane();
        Reglas = new javax.swing.JPanel();
        Configuracion = new javax.swing.JPanel();
        EmailClientes = new javax.swing.JPanel();
        buttonGroupEstado = new javax.swing.ButtonGroup();

        Sconnect_Mail.setAlignmentX(0.0F);
        Sconnect_Mail.setAlignmentY(0.0F);
        Sconnect_Mail.setMaximumSize(new java.awt.Dimension(1036, 630));
        Sconnect_Mail.setMinimumSize(new java.awt.Dimension(1036, 630));
        Sconnect_Mail.setName("Sconnect_Mail"); // NOI18N
        Sconnect_Mail.setPreferredSize(new java.awt.Dimension(1036, 630));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sconnectmail.SconnectMailApp.class).getContext().getResourceMap(SconnectMailView.class);
        Navegador.setBackground(resourceMap.getColor("Navegador.background")); // NOI18N
        Navegador.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Navegador.setMaximumSize(new java.awt.Dimension(189, 433));
        Navegador.setMinimumSize(new java.awt.Dimension(189, 433));
        Navegador.setName("Navegador"); // NOI18N
        Navegador.setPreferredSize(new java.awt.Dimension(189, 433));
        Navegador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EtiquetaPrincipal.setBackground(resourceMap.getColor("EtiquetaPrincipal.background")); // NOI18N
        EtiquetaPrincipal.setFont(resourceMap.getFont("EtiquetaPrincipal.font")); // NOI18N
        EtiquetaPrincipal.setForeground(resourceMap.getColor("EtiquetaPrincipal.foreground")); // NOI18N
        EtiquetaPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaPrincipal.setText(resourceMap.getString("EtiquetaPrincipal.text")); // NOI18N
        EtiquetaPrincipal.setAlignmentY(0.0F);
        EtiquetaPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, resourceMap.getColor("EtiquetaPrincipal.border.highlightOuterColor"), resourceMap.getColor("EtiquetaPrincipal.border.highlightInnerColor"), resourceMap.getColor("EtiquetaPrincipal.border.shadowOuterColor"), resourceMap.getColor("EtiquetaPrincipal.border.shadowInnerColor"))); // NOI18N
        EtiquetaPrincipal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EtiquetaPrincipal.setMaximumSize(new java.awt.Dimension(189, 25));
        EtiquetaPrincipal.setMinimumSize(new java.awt.Dimension(189, 25));
        EtiquetaPrincipal.setName("EtiquetaPrincipal"); // NOI18N
        EtiquetaPrincipal.setOpaque(true);
        EtiquetaPrincipal.setPreferredSize(new java.awt.Dimension(189, 25));
        Navegador.add(EtiquetaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BotonReglas.setIcon(resourceMap.getIcon("BotonReglas.icon")); // NOI18N
        BotonReglas.setBorderPainted(false);
        BotonReglas.setContentAreaFilled(false);
        BotonReglas.setFocusPainted(false);
        BotonReglas.setMaximumSize(new java.awt.Dimension(190, 60));
        BotonReglas.setMinimumSize(new java.awt.Dimension(190, 60));
        BotonReglas.setName("BotonReglas"); // NOI18N
        BotonReglas.setPreferredSize(new java.awt.Dimension(190, 60));
        BotonReglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReglasActionPerformed(evt);
            }
        });
        Navegador.add(BotonReglas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        EtiquetaReglas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaReglas.setText(resourceMap.getString("EtiquetaReglas.text")); // NOI18N
        EtiquetaReglas.setName("EtiquetaReglas"); // NOI18N
        Navegador.add(EtiquetaReglas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 190, 20));

        BotonConfiguracion.setIcon(resourceMap.getIcon("BotonConfiguracion.icon")); // NOI18N
        BotonConfiguracion.setBorderPainted(false);
        BotonConfiguracion.setContentAreaFilled(false);
        BotonConfiguracion.setFocusPainted(false);
        BotonConfiguracion.setMaximumSize(new java.awt.Dimension(190, 60));
        BotonConfiguracion.setMinimumSize(new java.awt.Dimension(190, 60));
        BotonConfiguracion.setName("BotonConfiguracion"); // NOI18N
        BotonConfiguracion.setPreferredSize(new java.awt.Dimension(190, 60));
        BotonConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConfiguracionActionPerformed(evt);
            }
        });
        Navegador.add(BotonConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        EtiquetaConfig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaConfig.setText(resourceMap.getString("EtiquetaConfig.text")); // NOI18N
        EtiquetaConfig.setName("EtiquetaConfig"); // NOI18N
        Navegador.add(EtiquetaConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 190, 20));

        BotonEmailClientes.setIcon(resourceMap.getIcon("BotonEmailClientes.icon")); // NOI18N
        BotonEmailClientes.setBorderPainted(false);
        BotonEmailClientes.setContentAreaFilled(false);
        BotonEmailClientes.setFocusPainted(false);
        BotonEmailClientes.setMaximumSize(new java.awt.Dimension(190, 60));
        BotonEmailClientes.setMinimumSize(new java.awt.Dimension(190, 60));
        BotonEmailClientes.setName("BotonEmailClientes"); // NOI18N
        BotonEmailClientes.setPreferredSize(new java.awt.Dimension(190, 60));
        BotonEmailClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEmailClientesActionPerformed(evt);
            }
        });
        Navegador.add(BotonEmailClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        EtiquetaEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaEmail.setText(resourceMap.getString("EtiquetaEmail.text")); // NOI18N
        EtiquetaEmail.setName("EtiquetaEmail"); // NOI18N
        Navegador.add(EtiquetaEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 190, 20));

        Contenido.setAlignmentX(0.0F);
        Contenido.setAlignmentY(0.0F);
        Contenido.setMaximumSize(new java.awt.Dimension(837, 640));
        Contenido.setMinimumSize(new java.awt.Dimension(837, 640));
        Contenido.setName("Contenido"); // NOI18N
        Contenido.setPreferredSize(new java.awt.Dimension(847, 640));

        CapasContenido.setAlignmentX(0.0F);
        CapasContenido.setAlignmentY(0.0F);
        CapasContenido.setMaximumSize(new java.awt.Dimension(837, 632));
        CapasContenido.setMinimumSize(new java.awt.Dimension(837, 632));
        CapasContenido.setName("CapasContenido"); // NOI18N

        Reglas.setAlignmentX(0.0F);
        Reglas.setAlignmentY(0.0F);
        Reglas.setMaximumSize(new java.awt.Dimension(837, 640));
        Reglas.setMinimumSize(new java.awt.Dimension(837, 640));
        Reglas.setName("Reglas"); // NOI18N
        Reglas.setPreferredSize(new java.awt.Dimension(837, 640));

        javax.swing.GroupLayout ReglasLayout = new javax.swing.GroupLayout(Reglas);
        Reglas.setLayout(ReglasLayout);
        ReglasLayout.setHorizontalGroup(
            ReglasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        ReglasLayout.setVerticalGroup(
            ReglasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        Reglas.setBounds(-3, 0, 840, 630);
        CapasContenido.add(Reglas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Configuracion.setAlignmentX(0.0F);
        Configuracion.setAlignmentY(0.0F);
        Configuracion.setMaximumSize(new java.awt.Dimension(837, 640));
        Configuracion.setMinimumSize(new java.awt.Dimension(837, 640));
        Configuracion.setName("Configuracion"); // NOI18N

        javax.swing.GroupLayout ConfiguracionLayout = new javax.swing.GroupLayout(Configuracion);
        Configuracion.setLayout(ConfiguracionLayout);
        ConfiguracionLayout.setHorizontalGroup(
            ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        ConfiguracionLayout.setVerticalGroup(
            ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        Configuracion.setBounds(-3, 0, 840, 630);
        CapasContenido.add(Configuracion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        EmailClientes.setAlignmentX(0.0F);
        EmailClientes.setAlignmentY(0.0F);
        EmailClientes.setMaximumSize(new java.awt.Dimension(837, 640));
        EmailClientes.setMinimumSize(new java.awt.Dimension(837, 640));
        EmailClientes.setName("EmailClientes"); // NOI18N

        javax.swing.GroupLayout EmailClientesLayout = new javax.swing.GroupLayout(EmailClientes);
        EmailClientes.setLayout(EmailClientesLayout);
        EmailClientesLayout.setHorizontalGroup(
            EmailClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        EmailClientesLayout.setVerticalGroup(
            EmailClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        EmailClientes.setBounds(-3, 0, 840, 630);
        CapasContenido.add(EmailClientes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CapasContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addComponent(CapasContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Sconnect_MailLayout = new javax.swing.GroupLayout(Sconnect_Mail);
        Sconnect_Mail.setLayout(Sconnect_MailLayout);
        Sconnect_MailLayout.setHorizontalGroup(
            Sconnect_MailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Sconnect_MailLayout.createSequentialGroup()
                .addComponent(Navegador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Sconnect_MailLayout.setVerticalGroup(
            Sconnect_MailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sconnect_MailLayout.createSequentialGroup()
                .addGroup(Sconnect_MailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Navegador, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118))
        );

        setComponent(Sconnect_Mail);
    }// </editor-fold>//GEN-END:initComponents

private void BotonReglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReglasActionPerformed
    Configuracion.setVisible(false);
    EmailClientes.setVisible(false);
    
    Reglas reglas = new Reglas();
    Reglas.add(reglas);
    layout(Reglas,reglas);
    
    Reglas.setVisible(true);
}//GEN-LAST:event_BotonReglasActionPerformed

private void BotonConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConfiguracionActionPerformed
    Reglas.setVisible(false);    
    EmailClientes.setVisible(false);
    
    Configuracion config = new Configuracion();
    Configuracion.add(config);
    layout(Configuracion,config);
    
    Configuracion.setVisible(true);
}//GEN-LAST:event_BotonConfiguracionActionPerformed

private void BotonEmailClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEmailClientesActionPerformed
    Reglas.setVisible(false);
    Configuracion.setVisible(false);
    
    Clientes clientes = new Clientes();
    EmailClientes.add(clientes);
    layout(EmailClientes,clientes);
    
    EmailClientes.setVisible(true);
}//GEN-LAST:event_BotonEmailClientesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonConfiguracion;
    private javax.swing.JButton BotonEmailClientes;
    private javax.swing.JButton BotonReglas;
    private javax.swing.JLayeredPane CapasContenido;
    private javax.swing.JPanel Configuracion;
    private javax.swing.JPanel Contenido;
    private javax.swing.JPanel EmailClientes;
    private javax.swing.JLabel EtiquetaConfig;
    private javax.swing.JLabel EtiquetaEmail;
    private javax.swing.JLabel EtiquetaPrincipal;
    private javax.swing.JLabel EtiquetaReglas;
    private javax.swing.JPanel Navegador;
    private javax.swing.JPanel Reglas;
    private javax.swing.JPanel Sconnect_Mail;
    private javax.swing.ButtonGroup buttonGroupEstado;
    // End of variables declaration//GEN-END:variables

       
    public void layout(JPanel local, JPanel externo){
    
        javax.swing.GroupLayout nuevoLayout = new javax.swing.GroupLayout(local);
        local.setLayout(nuevoLayout);
        nuevoLayout.setHorizontalGroup(
            nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(externo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        nuevoLayout.setVerticalGroup(
            nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(externo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        
    }
}
