/*
 * ConfiguracionMatcher.java
 *
 * Created on 4 de julio de 2008, 02:23 PM
 */

package sconnectmail;

import BD.ManejadorBD;
import BD.ValidarEmail;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import org.openswing.swing.client.OptionPane;


/**
 *
 * @author  pbcgvb
 */
public class Clientes extends javax.swing.JPanel {
    
    /** Creates new form ConfiguracionMatcher */
    public Clientes(){ 
     
        initComponents();
        PanelAgregarClientes.setVisible(false);
        PanelDetallesClientes.setVisible(true);
        
        ClientesTable.setColumnSelectionInterval(0,1);
        try{
            Cliente1.setText((String) ClientesTable.getValueAt(ClientesTable.getSelectedRow(), 0));
            Correo1.setText((String) ClientesTable.getValueAt(ClientesTable.getSelectedRow(), 1));        
        }catch(Exception e){}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Explorador = new javax.swing.JFrame();
        FileChooser = new javax.swing.JFileChooser();
        ParametrosGenerales = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        ContenedorClientes = new javax.swing.JScrollPane();
        ClientesTable = new javax.swing.JTable();
        Agregar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        ParametrosGenerales1 = new javax.swing.JPanel();
        ContenedorEventosClientes = new javax.swing.JLayeredPane();
        PanelDetallesClientes = new javax.swing.JPanel();
        TituloDetalleCliente = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        LabelCorreo1 = new javax.swing.JLabel();
        Correo1 = new javax.swing.JFormattedTextField();
        Cliente1 = new javax.swing.JTextField();
        LabelCliente1 = new javax.swing.JLabel();
        EditarCliente = new javax.swing.JButton();
        CancelarEditarCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PanelAgregarClientes = new javax.swing.JPanel();
        TituloAgregarCliente = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        LabelCorreo2 = new javax.swing.JLabel();
        Correo2 = new javax.swing.JFormattedTextField();
        Cliente2 = new javax.swing.JTextField();
        LabelCliente2 = new javax.swing.JLabel();
        AgregarCliente = new javax.swing.JButton();
        CancelarAgregarCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        Explorador.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sconnectmail.SconnectMailApp.class).getContext().getResourceMap(Clientes.class);
        Explorador.setTitle(resourceMap.getString("Explorador.title")); // NOI18N
        Explorador.setName("Explorador"); // NOI18N

        FileChooser.setDialogTitle(resourceMap.getString("FileChooser.dialogTitle")); // NOI18N
        FileChooser.setName("FileChooser"); // NOI18N

        javax.swing.GroupLayout ExploradorLayout = new javax.swing.GroupLayout(Explorador.getContentPane());
        Explorador.getContentPane().setLayout(ExploradorLayout);
        ExploradorLayout.setHorizontalGroup(
            ExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
            .addGroup(ExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExploradorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ExploradorLayout.setVerticalGroup(
            ExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
            .addGroup(ExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExploradorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setMaximumSize(new java.awt.Dimension(837, 640));
        setMinimumSize(new java.awt.Dimension(837, 640));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(837, 640));

        ParametrosGenerales.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ParametrosGenerales.setMaximumSize(new java.awt.Dimension(805, 300));
        ParametrosGenerales.setMinimumSize(new java.awt.Dimension(805, 300));
        ParametrosGenerales.setName("ParametrosGenerales"); // NOI18N
        ParametrosGenerales.setPreferredSize(new java.awt.Dimension(805, 300));
        ParametrosGenerales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(resourceMap.getColor("Titulo.background")); // NOI18N
        Titulo.setFont(resourceMap.getFont("Titulo.font")); // NOI18N
        Titulo.setForeground(resourceMap.getColor("Titulo.foreground")); // NOI18N
        Titulo.setText(resourceMap.getString("Titulo.text")); // NOI18N
        Titulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Titulo.setMaximumSize(new java.awt.Dimension(800, 28));
        Titulo.setMinimumSize(new java.awt.Dimension(800, 28));
        Titulo.setName("Titulo"); // NOI18N
        Titulo.setOpaque(true);
        Titulo.setPreferredSize(new java.awt.Dimension(800, 28));
        ParametrosGenerales.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, -1));

        ContenedorClientes.setName("ContenedorClientes"); // NOI18N

        ClientesTable.setAutoCreateRowSorter(true);
        ClientesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ClientesTable.setName("ClientesTable"); // NOI18N
        org.jdesktop.beansbinding.BindingGroup bindingGroup;
        java.util.List<Objetos.Cliente> clienteList;
        javax.persistence.Query clienteQuery;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();
        javax.persistence.EntityManager AlertasSwiftPUEntityManager;
        AlertasSwiftPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("AlertasSwiftPU").createEntityManager();
        clienteQuery = java.beans.Beans.isDesignTime() ? null : AlertasSwiftPUEntityManager.createQuery("SELECT c FROM Cliente c");

        clienteList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : clienteQuery.getResultList();
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, clienteList, ClientesTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombre}"));
        columnBinding.setColumnName("Núm. Cuenta Cliente");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${mail}"));
        columnBinding.setColumnName("Correo(s)");
        columnBinding.setColumnClass(String.class);
        jTableBinding.bind();

        ClientesTable.getColumnModel().getColumn(0).setMaxWidth(200);
        ClientesTable.getColumnModel().getColumn(0).setMinWidth(200);
        ClientesTable.getColumnModel().getColumn(1).setMaxWidth(450);
        ClientesTable.getColumnModel().getColumn(1).setMinWidth(450);
        try{ClientesTable.addRowSelectionInterval(0,0);}catch(Exception e){}
        ClientesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientesTableMouseClicked(evt);
            }
        });
        ClientesTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ClientesTableKeyReleased(evt);
            }
        });
        ContenedorClientes.setViewportView(ClientesTable);

        ParametrosGenerales.add(ContenedorClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 640, 220));

        Agregar.setText(resourceMap.getString("Agregar.text")); // NOI18N
        Agregar.setMaximumSize(new java.awt.Dimension(81, 23));
        Agregar.setMinimumSize(new java.awt.Dimension(81, 23));
        Agregar.setName("Agregar"); // NOI18N
        Agregar.setPreferredSize(new java.awt.Dimension(81, 23));
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        ParametrosGenerales.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 81, 23));

        Eliminar.setText(resourceMap.getString("Eliminar.text")); // NOI18N
        Eliminar.setMaximumSize(new java.awt.Dimension(81, 23));
        Eliminar.setMinimumSize(new java.awt.Dimension(81, 23));
        Eliminar.setName("Eliminar"); // NOI18N
        Eliminar.setPreferredSize(new java.awt.Dimension(81, 23));
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        ParametrosGenerales.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 81, 23));

        ParametrosGenerales1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ParametrosGenerales1.setMaximumSize(new java.awt.Dimension(805, 290));
        ParametrosGenerales1.setMinimumSize(new java.awt.Dimension(805, 290));
        ParametrosGenerales1.setName("ParametrosGenerales1"); // NOI18N
        ParametrosGenerales1.setPreferredSize(new java.awt.Dimension(805, 290));
        ParametrosGenerales1.setLayout(null);

        ContenedorEventosClientes.setMaximumSize(new java.awt.Dimension(805, 290));
        ContenedorEventosClientes.setMinimumSize(new java.awt.Dimension(805, 290));
        ContenedorEventosClientes.setName("ContenedorEventosClientes"); // NOI18N

        PanelDetallesClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelDetallesClientes.setMaximumSize(new java.awt.Dimension(805, 290));
        PanelDetallesClientes.setMinimumSize(new java.awt.Dimension(805, 290));
        PanelDetallesClientes.setName("PanelDetallesClientes"); // NOI18N
        PanelDetallesClientes.setPreferredSize(new java.awt.Dimension(805, 290));
        PanelDetallesClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloDetalleCliente.setBackground(resourceMap.getColor("TituloDetalleCliente.background")); // NOI18N
        TituloDetalleCliente.setFont(resourceMap.getFont("TituloDetalleCliente.font")); // NOI18N
        TituloDetalleCliente.setForeground(resourceMap.getColor("TituloDetalleCliente.foreground")); // NOI18N
        TituloDetalleCliente.setText(resourceMap.getString("TituloDetalleCliente.text")); // NOI18N
        TituloDetalleCliente.setAlignmentY(0.0F);
        TituloDetalleCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        TituloDetalleCliente.setMaximumSize(new java.awt.Dimension(801, 28));
        TituloDetalleCliente.setMinimumSize(new java.awt.Dimension(801, 28));
        TituloDetalleCliente.setName("TituloDetalleCliente"); // NOI18N
        TituloDetalleCliente.setOpaque(true);
        TituloDetalleCliente.setPreferredSize(new java.awt.Dimension(801, 28));
        PanelDetallesClientes.add(TituloDetalleCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setName("jPanel4"); // NOI18N

        LabelCorreo1.setText(resourceMap.getString("LabelCorreo1.text")); // NOI18N
        LabelCorreo1.setName("LabelCorreo1"); // NOI18N

        Correo1.setName("Correo1"); // NOI18N

        Cliente1.setName("Cliente1"); // NOI18N

        LabelCliente1.setText(resourceMap.getString("LabelCliente1.text")); // NOI18N
        LabelCliente1.setName("LabelCliente1"); // NOI18N

        EditarCliente.setText(resourceMap.getString("EditarCliente.text")); // NOI18N
        EditarCliente.setMaximumSize(new java.awt.Dimension(81, 23));
        EditarCliente.setMinimumSize(new java.awt.Dimension(81, 23));
        EditarCliente.setName("EditarCliente"); // NOI18N
        EditarCliente.setPreferredSize(new java.awt.Dimension(81, 23));
        EditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarClienteActionPerformed(evt);
            }
        });

        CancelarEditarCliente.setText(resourceMap.getString("CancelarEditarCliente.text")); // NOI18N
        CancelarEditarCliente.setMaximumSize(new java.awt.Dimension(81, 23));
        CancelarEditarCliente.setMinimumSize(new java.awt.Dimension(81, 23));
        CancelarEditarCliente.setName("CancelarEditarCliente"); // NOI18N
        CancelarEditarCliente.setPreferredSize(new java.awt.Dimension(81, 23));
        CancelarEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarEditarClienteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(EditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CancelarEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelCliente1)
                            .addComponent(LabelCorreo1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Correo1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCliente1)
                    .addComponent(Cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Correo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelarEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanelDetallesClientes.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 780, 230));

        PanelDetallesClientes.setBounds(0, 0, 805, 290);
        ContenedorEventosClientes.add(PanelDetallesClientes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        PanelAgregarClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelAgregarClientes.setMaximumSize(new java.awt.Dimension(805, 290));
        PanelAgregarClientes.setMinimumSize(new java.awt.Dimension(805, 290));
        PanelAgregarClientes.setName("PanelAgregarClientes"); // NOI18N
        PanelAgregarClientes.setPreferredSize(new java.awt.Dimension(805, 290));
        PanelAgregarClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloAgregarCliente.setBackground(resourceMap.getColor("TituloAgregarCliente.background")); // NOI18N
        TituloAgregarCliente.setFont(resourceMap.getFont("TituloAgregarCliente.font")); // NOI18N
        TituloAgregarCliente.setForeground(resourceMap.getColor("TituloAgregarCliente.foreground")); // NOI18N
        TituloAgregarCliente.setText(resourceMap.getString("TituloAgregarCliente.text")); // NOI18N
        TituloAgregarCliente.setAlignmentY(0.0F);
        TituloAgregarCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        TituloAgregarCliente.setMaximumSize(new java.awt.Dimension(801, 28));
        TituloAgregarCliente.setMinimumSize(new java.awt.Dimension(801, 28));
        TituloAgregarCliente.setName("TituloAgregarCliente"); // NOI18N
        TituloAgregarCliente.setOpaque(true);
        TituloAgregarCliente.setPreferredSize(new java.awt.Dimension(801, 28));
        PanelAgregarClientes.add(TituloAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setName("jPanel3"); // NOI18N

        LabelCorreo2.setText(resourceMap.getString("LabelCorreo2.text")); // NOI18N
        LabelCorreo2.setName("LabelCorreo2"); // NOI18N

        Correo2.setName("Correo2"); // NOI18N

        Cliente2.setName("Cliente2"); // NOI18N

        LabelCliente2.setText(resourceMap.getString("LabelCliente2.text")); // NOI18N
        LabelCliente2.setName("LabelCliente2"); // NOI18N

        AgregarCliente.setText(resourceMap.getString("AgregarCliente.text")); // NOI18N
        AgregarCliente.setMaximumSize(new java.awt.Dimension(81, 23));
        AgregarCliente.setMinimumSize(new java.awt.Dimension(81, 23));
        AgregarCliente.setName("AgregarCliente"); // NOI18N
        AgregarCliente.setPreferredSize(new java.awt.Dimension(81, 23));
        AgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarClienteActionPerformed(evt);
            }
        });

        CancelarAgregarCliente.setText(resourceMap.getString("CancelarAgregarCliente.text")); // NOI18N
        CancelarAgregarCliente.setMaximumSize(new java.awt.Dimension(81, 23));
        CancelarAgregarCliente.setMinimumSize(new java.awt.Dimension(81, 23));
        CancelarAgregarCliente.setName("CancelarAgregarCliente"); // NOI18N
        CancelarAgregarCliente.setPreferredSize(new java.awt.Dimension(81, 23));
        CancelarAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarAgregarClienteActionPerformed(evt);
            }
        });

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(586, Short.MAX_VALUE)
                .addComponent(AgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CancelarAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelCliente2)
                    .addComponent(LabelCorreo2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correo2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCliente2)
                    .addComponent(Cliente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Correo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelarAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanelAgregarClientes.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 780, 230));

        PanelAgregarClientes.setBounds(0, 0, 805, 290);
        ContenedorEventosClientes.add(PanelAgregarClientes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ParametrosGenerales1.add(ContenedorEventosClientes);
        ContenedorEventosClientes.setBounds(0, 0, 805, 290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ParametrosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ParametrosGenerales1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ParametrosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ParametrosGenerales1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

 
private void ClientesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientesTableMouseClicked
    try{
        Cliente1.setText((String) ClientesTable.getValueAt(ClientesTable.getSelectedRow(), 0));
        Correo1.setText((String) ClientesTable.getValueAt(ClientesTable.getSelectedRow(), 1));        
    }catch(Exception e){}
}//GEN-LAST:event_ClientesTableMouseClicked

private void ClientesTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClientesTableKeyReleased
    try{
        Cliente1.setText((String) ClientesTable.getValueAt(ClientesTable.getSelectedRow(), 0));
        Correo1.setText((String) ClientesTable.getValueAt(ClientesTable.getSelectedRow(), 1));        
    }catch(Exception e){}
}//GEN-LAST:event_ClientesTableKeyReleased

private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
    PanelAgregarClientes.setVisible(true);
    PanelDetallesClientes.setVisible(false);
}//GEN-LAST:event_AgregarActionPerformed

private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
    int opcion = OptionPane.showConfirmDialog(null,"Está seguro que desea eliminar el registro?","Advertencia",JOptionPane.WARNING_MESSAGE);  //0 Aceptar 
    
    if(opcion == 0){
        String codigoCliente = (String) ClientesTable.getValueAt(ClientesTable.getSelectedRow(), 0);
        ManejadorBD.deleteCliente(codigoCliente);
        Cliente1.setText("");
        Correo1.setText("");
        ManejadorBD.updateClientes(ClientesTable);  
        
        ClientesTable.getColumnModel().getColumn(0).setMaxWidth(200);
        ClientesTable.getColumnModel().getColumn(0).setMinWidth(200);
        ClientesTable.getColumnModel().getColumn(1).setMaxWidth(450);
        ClientesTable.getColumnModel().getColumn(1).setMinWidth(450);
    }
}//GEN-LAST:event_EliminarActionPerformed

    private void EditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarClienteActionPerformed
        int opcion = OptionPane.showConfirmDialog(null,"Está seguro que desea editar la información del registro?","Advertencia",JOptionPane.WARNING_MESSAGE);  //0 Aceptar 
    
        if(opcion == 0){
            if(paramVaciosEditar()){
                OptionPane.showMessageDialog(null,"Debe completar toda la información","Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                int result = ManejadorBD.setCliente(ClientesTable.getValueAt(ClientesTable.getSelectedRow(), 0).toString(),Cliente1.getText(),Correo1.getText());

                if(result == -1){
                        OptionPane.showMessageDialog(null,"Este Cliente ya se encuentra registrado","Error",JOptionPane.ERROR_MESSAGE);
                    }
                else if(result == 0){
                    OptionPane.showMessageDialog(null,"Error editando el cliente","Error",JOptionPane.ERROR_MESSAGE);
                }
                else{
                ManejadorBD.updateClientes(ClientesTable);     

                ClientesTable.getColumnModel().getColumn(0).setMaxWidth(200);
                ClientesTable.getColumnModel().getColumn(0).setMinWidth(200);
                ClientesTable.getColumnModel().getColumn(1).setMaxWidth(450);
                ClientesTable.getColumnModel().getColumn(1).setMinWidth(450);
                }
            }    
        }
        
    }//GEN-LAST:event_EditarClienteActionPerformed

    private void CancelarEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarEditarClienteActionPerformed
        ManejadorBD.updateClientes(ClientesTable);     
        
    }//GEN-LAST:event_CancelarEditarClienteActionPerformed

    private void AgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarClienteActionPerformed
        if(paramVaciosAgregar()){
            OptionPane.showMessageDialog(null,"Debe completar toda la información","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
//            if(correoesValido()){
                int result = ManejadorBD.setCliente("",Cliente2.getText(),Correo2.getText());
                
                if(result == -1){
                    OptionPane.showMessageDialog(null,"Este Cliente ya se encuentra registrado","Error",JOptionPane.ERROR_MESSAGE);
                }
                else if(result == 0){
                    OptionPane.showMessageDialog(null,"Error registrando el cliente","Error",JOptionPane.ERROR_MESSAGE);
                }
                else{
                ManejadorBD.updateClientes(ClientesTable);
                
                ClientesTable.getColumnModel().getColumn(0).setMaxWidth(200);
                ClientesTable.getColumnModel().getColumn(0).setMinWidth(200);
                ClientesTable.getColumnModel().getColumn(1).setMaxWidth(450);
                ClientesTable.getColumnModel().getColumn(1).setMinWidth(450);

                PanelAgregarClientes.setVisible(false);
                PanelDetallesClientes.setVisible(true);
                Cliente2.setText("");
                Correo2.setText("");   
                }
//            }    
//            else{
//                OptionPane.showMessageDialog(null,"Debe introducir un correo válido","Error",JOptionPane.ERROR_MESSAGE);
//            }
        }
        
    }//GEN-LAST:event_AgregarClienteActionPerformed

    private void CancelarAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarAgregarClienteActionPerformed
       PanelAgregarClientes.setVisible(false);
       PanelDetallesClientes.setVisible(true);
       Cliente2.setText("");
       Correo2.setText("");        
    }//GEN-LAST:event_CancelarAgregarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton AgregarCliente;
    private javax.swing.JButton CancelarAgregarCliente;
    private javax.swing.JButton CancelarEditarCliente;
    private javax.swing.JTextField Cliente1;
    private javax.swing.JTextField Cliente2;
    private javax.swing.JTable ClientesTable;
    private javax.swing.JScrollPane ContenedorClientes;
    private javax.swing.JLayeredPane ContenedorEventosClientes;
    private javax.swing.JFormattedTextField Correo1;
    private javax.swing.JFormattedTextField Correo2;
    private javax.swing.JButton EditarCliente;
    private javax.swing.JButton Eliminar;
    private javax.swing.JFrame Explorador;
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JLabel LabelCliente1;
    private javax.swing.JLabel LabelCliente2;
    private javax.swing.JLabel LabelCorreo1;
    private javax.swing.JLabel LabelCorreo2;
    private javax.swing.JPanel PanelAgregarClientes;
    private javax.swing.JPanel PanelDetallesClientes;
    private javax.swing.JPanel ParametrosGenerales;
    private javax.swing.JPanel ParametrosGenerales1;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel TituloAgregarCliente;
    private javax.swing.JLabel TituloDetalleCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

   DefaultTableModel modelo = new DefaultTableModel();
    
   public boolean paramVaciosAgregar(){
        if(Cliente2.getText().isEmpty() || Correo2.getText().isEmpty()){return true;}
        else{return false;}
   }
   
   public boolean paramVaciosEditar(){
        if(Cliente1.getText().isEmpty() || Correo1.getText().isEmpty()){return true;}
        else{return false;}
   }
   

    private boolean correoesValido() {
        ValidarEmail emailValidator = new ValidarEmail ();
        
        if(!emailValidator.validate(Correo2.getText().trim())) {
            System.out.print("Invalid Email ID");
            return false;            
        }
        else{return true;}
    }
    
   
}
