/*
 * ConfiguracionMatcher.java
 *
 * Created on 4 de julio de 2008, 02:23 PM
 */

package sconnectmail;

import BD.DesEncrypter;
import BD.ManejadorBD;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import org.openswing.swing.client.OptionPane;


/**
 *
 * @author  pbcgvb
 */
public class Configuracion extends javax.swing.JPanel {
    
    /** Creates new form ConfiguracionMatcher */
    public Configuracion(){ 
     
        initComponents();
        ParametrosGenerales.setVisible(true);   
        setDatosConfiguracion();        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Explorador = new javax.swing.JFrame();
        FileChooser = new javax.swing.JFileChooser();
        ParametrosGenerales = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        PanelDirectorios = new javax.swing.JPanel();
        LabelEntrada = new javax.swing.JLabel();
        LabelProcesado = new javax.swing.JLabel();
        LabelLog = new javax.swing.JLabel();
        Entrada = new javax.swing.JTextField();
        Procesado = new javax.swing.JTextField();
        Log = new javax.swing.JTextField();
        ExaminarEntrada = new javax.swing.JButton();
        ExaminarProcesado = new javax.swing.JButton();
        ExaminarLog = new javax.swing.JButton();
        PanelSeguridad = new javax.swing.JPanel();
        LabelServidor = new javax.swing.JLabel();
        LabelPuerto = new javax.swing.JLabel();
        Servidor = new javax.swing.JTextField();
        Puerto = new javax.swing.JTextField();
        LabelServidor1 = new javax.swing.JLabel();
        panelSMTP = new javax.swing.JPanel();
        LabelUsuario = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        LabelContrasena = new javax.swing.JLabel();
        Contrasena = new javax.swing.JPasswordField();
        Plantilla = new javax.swing.JButton();
        Aceptar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        Explorador.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sconnectmail.SconnectMailApp.class).getContext().getResourceMap(Configuracion.class);
        Explorador.setTitle(resourceMap.getString("Explorador.title")); // NOI18N
        Explorador.setName("Explorador"); // NOI18N

        FileChooser.setDialogTitle(resourceMap.getString("FileChooser.dialogTitle")); // NOI18N
        FileChooser.setName("FileChooser"); // NOI18N

        javax.swing.GroupLayout ExploradorLayout = new javax.swing.GroupLayout(Explorador.getContentPane());
        Explorador.getContentPane().setLayout(ExploradorLayout);
        ExploradorLayout.setHorizontalGroup(
            ExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
            .addGroup(ExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExploradorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ExploradorLayout.setVerticalGroup(
            ExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
            .addGroup(ExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExploradorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setMaximumSize(new java.awt.Dimension(837, 640));
        setMinimumSize(new java.awt.Dimension(837, 640));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(837, 640));

        ParametrosGenerales.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ParametrosGenerales.setMaximumSize(new java.awt.Dimension(443, 430));
        ParametrosGenerales.setMinimumSize(new java.awt.Dimension(805, 430));
        ParametrosGenerales.setName("ParametrosGenerales"); // NOI18N
        ParametrosGenerales.setPreferredSize(new java.awt.Dimension(805, 430));

        Titulo.setBackground(resourceMap.getColor("Titulo.background")); // NOI18N
        Titulo.setFont(resourceMap.getFont("Titulo.font")); // NOI18N
        Titulo.setForeground(resourceMap.getColor("Titulo.foreground")); // NOI18N
        Titulo.setText(resourceMap.getString("Titulo.text")); // NOI18N
        Titulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Titulo.setMaximumSize(new java.awt.Dimension(800, 28));
        Titulo.setMinimumSize(new java.awt.Dimension(800, 28));
        Titulo.setName("Titulo"); // NOI18N
        Titulo.setOpaque(true);
        Titulo.setPreferredSize(new java.awt.Dimension(800, 28));

        PanelDirectorios.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("PanelDirectorios.border.border.lineColor")), resourceMap.getString("PanelDirectorios.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("PanelDirectorios.border.titleFont"), resourceMap.getColor("PanelDirectorios.border.titleColor"))); // NOI18N
        PanelDirectorios.setMaximumSize(new java.awt.Dimension(785, 100));
        PanelDirectorios.setMinimumSize(new java.awt.Dimension(785, 100));
        PanelDirectorios.setName("PanelDirectorios"); // NOI18N
        PanelDirectorios.setPreferredSize(new java.awt.Dimension(785, 100));
        PanelDirectorios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelEntrada.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelEntrada.setText(resourceMap.getString("LabelEntrada.text")); // NOI18N
        LabelEntrada.setName("LabelEntrada"); // NOI18N
        PanelDirectorios.add(LabelEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, 20));

        LabelProcesado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelProcesado.setText(resourceMap.getString("LabelProcesado.text")); // NOI18N
        LabelProcesado.setName("LabelProcesado"); // NOI18N
        PanelDirectorios.add(LabelProcesado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, 20));

        LabelLog.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelLog.setText(resourceMap.getString("LabelLog.text")); // NOI18N
        LabelLog.setName("LabelLog"); // NOI18N
        PanelDirectorios.add(LabelLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 70, 20));

        Entrada.setText(resourceMap.getString("Entrada.text")); // NOI18N
        Entrada.setMaximumSize(new java.awt.Dimension(200, 20));
        Entrada.setMinimumSize(new java.awt.Dimension(200, 20));
        Entrada.setName("Entrada"); // NOI18N
        Entrada.setPreferredSize(new java.awt.Dimension(200, 20));
        PanelDirectorios.add(Entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 200, -1));

        Procesado.setText(resourceMap.getString("Procesado.text")); // NOI18N
        Procesado.setMaximumSize(new java.awt.Dimension(200, 20));
        Procesado.setMinimumSize(new java.awt.Dimension(200, 20));
        Procesado.setName("Procesado"); // NOI18N
        Procesado.setPreferredSize(new java.awt.Dimension(200, 20));
        PanelDirectorios.add(Procesado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 200, -1));

        Log.setText(resourceMap.getString("Log.text")); // NOI18N
        Log.setMaximumSize(new java.awt.Dimension(200, 20));
        Log.setMinimumSize(new java.awt.Dimension(200, 20));
        Log.setName("Log"); // NOI18N
        Log.setPreferredSize(new java.awt.Dimension(200, 20));
        PanelDirectorios.add(Log, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 200, -1));

        ExaminarEntrada.setIcon(resourceMap.getIcon("ExaminarEntrada.icon")); // NOI18N
        ExaminarEntrada.setText(resourceMap.getString("ExaminarEntrada.text")); // NOI18N
        ExaminarEntrada.setFocusPainted(false);
        ExaminarEntrada.setName("ExaminarEntrada"); // NOI18N
        ExaminarEntrada.setPreferredSize(new java.awt.Dimension(20, 20));
        ExaminarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExaminarEntradaActionPerformed(evt);
            }
        });
        PanelDirectorios.add(ExaminarEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        ExaminarProcesado.setIcon(resourceMap.getIcon("ExaminarProcesado.icon")); // NOI18N
        ExaminarProcesado.setText(resourceMap.getString("ExaminarProcesado.text")); // NOI18N
        ExaminarProcesado.setName("ExaminarProcesado"); // NOI18N
        ExaminarProcesado.setPreferredSize(new java.awt.Dimension(20, 20));
        ExaminarProcesado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExaminarProcesadoActionPerformed(evt);
            }
        });
        PanelDirectorios.add(ExaminarProcesado, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        ExaminarLog.setIcon(resourceMap.getIcon("ExaminarLog.icon")); // NOI18N
        ExaminarLog.setText(resourceMap.getString("ExaminarLog.text")); // NOI18N
        ExaminarLog.setName("ExaminarLog"); // NOI18N
        ExaminarLog.setPreferredSize(new java.awt.Dimension(20, 20));
        ExaminarLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExaminarLogActionPerformed(evt);
            }
        });
        PanelDirectorios.add(ExaminarLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        PanelSeguridad.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("PanelSeguridad.border.border.lineColor")), resourceMap.getString("PanelSeguridad.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("PanelSeguridad.border.titleFont"), resourceMap.getColor("PanelSeguridad.border.titleColor"))); // NOI18N
        PanelSeguridad.setName("PanelSeguridad"); // NOI18N
        PanelSeguridad.setPreferredSize(new java.awt.Dimension(785, 200));
        PanelSeguridad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelServidor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelServidor.setText(resourceMap.getString("LabelServidor.text")); // NOI18N
        LabelServidor.setName("LabelServidor"); // NOI18N
        PanelSeguridad.add(LabelServidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 110, 20));

        LabelPuerto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelPuerto.setText(resourceMap.getString("LabelPuerto.text")); // NOI18N
        LabelPuerto.setName("LabelPuerto"); // NOI18N
        PanelSeguridad.add(LabelPuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 70, 20));

        Servidor.setText(resourceMap.getString("Servidor.text")); // NOI18N
        Servidor.setName("Servidor"); // NOI18N
        Servidor.setPreferredSize(new java.awt.Dimension(230, 20));
        PanelSeguridad.add(Servidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        Puerto.setText(resourceMap.getString("Puerto.text")); // NOI18N
        Puerto.setMaximumSize(new java.awt.Dimension(60, 20));
        Puerto.setMinimumSize(new java.awt.Dimension(60, 20));
        Puerto.setName("Puerto"); // NOI18N
        Puerto.setPreferredSize(new java.awt.Dimension(60, 20));
        PanelSeguridad.add(Puerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 60, -1));

        LabelServidor1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelServidor1.setText(resourceMap.getString("LabelServidor1.text")); // NOI18N
        LabelServidor1.setName("LabelServidor1"); // NOI18N
        PanelSeguridad.add(LabelServidor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 20));

        panelSMTP.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), resourceMap.getString("panelSMTP.border.title"))); // NOI18N
        panelSMTP.setName("panelSMTP"); // NOI18N

        LabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelUsuario.setText(resourceMap.getString("LabelUsuario.text")); // NOI18N
        LabelUsuario.setName("LabelUsuario"); // NOI18N

        Usuario.setText(resourceMap.getString("Usuario.text")); // NOI18N
        Usuario.setName("Usuario"); // NOI18N
        Usuario.setPreferredSize(new java.awt.Dimension(150, 20));

        LabelContrasena.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelContrasena.setText(resourceMap.getString("LabelContrasena.text")); // NOI18N
        LabelContrasena.setName("LabelContrasena"); // NOI18N

        Contrasena.setText(resourceMap.getString("Contrasena.text")); // NOI18N
        Contrasena.setMaximumSize(new java.awt.Dimension(150, 20));
        Contrasena.setMinimumSize(new java.awt.Dimension(150, 20));
        Contrasena.setName("Contrasena"); // NOI18N
        Contrasena.setPreferredSize(new java.awt.Dimension(150, 20));

        javax.swing.GroupLayout panelSMTPLayout = new javax.swing.GroupLayout(panelSMTP);
        panelSMTP.setLayout(panelSMTPLayout);
        panelSMTPLayout.setHorizontalGroup(
            panelSMTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSMTPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSMTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSMTPLayout.createSequentialGroup()
                        .addComponent(LabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSMTPLayout.createSequentialGroup()
                        .addComponent(LabelContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        panelSMTPLayout.setVerticalGroup(
            panelSMTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSMTPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSMTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelSMTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        PanelSeguridad.add(panelSMTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 350, 110));

        Plantilla.setText(resourceMap.getString("Plantilla.text")); // NOI18N
        Plantilla.setMaximumSize(new java.awt.Dimension(81, 23));
        Plantilla.setMinimumSize(new java.awt.Dimension(81, 23));
        Plantilla.setName("Plantilla"); // NOI18N
        Plantilla.setPreferredSize(new java.awt.Dimension(81, 23));
        Plantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlantillaActionPerformed(evt);
            }
        });
        PanelSeguridad.add(Plantilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 150, -1));

        Aceptar.setText(resourceMap.getString("Aceptar.text")); // NOI18N
        Aceptar.setLabel(resourceMap.getString("Aceptar.label")); // NOI18N
        Aceptar.setMaximumSize(new java.awt.Dimension(81, 23));
        Aceptar.setMinimumSize(new java.awt.Dimension(81, 23));
        Aceptar.setName("Aceptar"); // NOI18N
        Aceptar.setPreferredSize(new java.awt.Dimension(81, 23));
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Cancelar.setText(resourceMap.getString("Cancelar.text")); // NOI18N
        Cancelar.setLabel(resourceMap.getString("Cancelar.label")); // NOI18N
        Cancelar.setMaximumSize(new java.awt.Dimension(81, 23));
        Cancelar.setMinimumSize(new java.awt.Dimension(81, 23));
        Cancelar.setName("Cancelar"); // NOI18N
        Cancelar.setPreferredSize(new java.awt.Dimension(81, 23));

        javax.swing.GroupLayout ParametrosGeneralesLayout = new javax.swing.GroupLayout(ParametrosGenerales);
        ParametrosGenerales.setLayout(ParametrosGeneralesLayout);
        ParametrosGeneralesLayout.setHorizontalGroup(
            ParametrosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ParametrosGeneralesLayout.createSequentialGroup()
                .addContainerGap(619, Short.MAX_VALUE)
                .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(ParametrosGeneralesLayout.createSequentialGroup()
                .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(ParametrosGeneralesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelDirectorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(ParametrosGeneralesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        ParametrosGeneralesLayout.setVerticalGroup(
            ParametrosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ParametrosGeneralesLayout.createSequentialGroup()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelDirectorios, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(PanelSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(ParametrosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ParametrosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ParametrosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

 
private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
   if (mensajeConfirmCambio() == 0){    
                  
            Vector datos = new Vector();

            datos.add(Entrada.getText());
            datos.add(Procesado.getText());
            datos.add(Log.getText());
            datos.add(Servidor.getText());
            datos.add(Puerto.getText());         
            datos.add(Usuario.getText());           
            if(Contrasena.getPassword() != null){datos.add(Contrasena.getText());}else{datos.add("");}   
                        
            ManejadorBD.setConfiguracion(datos);            
        }
    
}//GEN-LAST:event_AceptarActionPerformed

private void ExaminarLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExaminarLogActionPerformed
    FileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    int returnVal = FileChooser.showSaveDialog(Configuracion.this);
    
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        Log.setText(FileChooser.getSelectedFile().toString());                
    }         
    
    Explorador.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
}//GEN-LAST:event_ExaminarLogActionPerformed

private void ExaminarProcesadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExaminarProcesadoActionPerformed
    FileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    int returnVal = FileChooser.showSaveDialog(Configuracion.this);
    
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        Procesado.setText(FileChooser.getSelectedFile().toString());                
    }         
    
    Explorador.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
}//GEN-LAST:event_ExaminarProcesadoActionPerformed

private void ExaminarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExaminarEntradaActionPerformed
    FileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    int returnVal = FileChooser.showSaveDialog(Configuracion.this);
    
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        Entrada.setText(FileChooser.getSelectedFile().toString());                
    }         
    
    Explorador.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
}//GEN-LAST:event_ExaminarEntradaActionPerformed

private void PlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlantillaActionPerformed
    JFrame mainFrame = SconnectMailApp.getApplication().getMainFrame();
    PlantillaCorreo plantilla = new PlantillaCorreo();
    plantilla.setLocationRelativeTo(mainFrame);

    SconnectMailApp.getApplication().show(plantilla);// TODO add your handling code here:
}//GEN-LAST:event_PlantillaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JPasswordField Contrasena;
    private javax.swing.JTextField Entrada;
    private javax.swing.JButton ExaminarEntrada;
    private javax.swing.JButton ExaminarLog;
    private javax.swing.JButton ExaminarProcesado;
    private javax.swing.JFrame Explorador;
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JLabel LabelContrasena;
    private javax.swing.JLabel LabelEntrada;
    private javax.swing.JLabel LabelLog;
    private javax.swing.JLabel LabelProcesado;
    private javax.swing.JLabel LabelPuerto;
    private javax.swing.JLabel LabelServidor;
    private javax.swing.JLabel LabelServidor1;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JTextField Log;
    private javax.swing.JPanel PanelDirectorios;
    private javax.swing.JPanel PanelSeguridad;
    private javax.swing.JPanel ParametrosGenerales;
    private javax.swing.JButton Plantilla;
    private javax.swing.JTextField Procesado;
    private javax.swing.JTextField Puerto;
    private javax.swing.JTextField Servidor;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField Usuario;
    private javax.swing.JPanel panelSMTP;
    // End of variables declaration//GEN-END:variables

   
    
   
    private int mensajeConfirmCambio(){
        String mensaje = "Está seguro que desea cambiar la configuración";
        String titulo = "Advertencia";
        int opcion = OptionPane.showConfirmDialog(null,mensaje,titulo,JOptionPane.YES_NO_OPTION);  //0 Aceptar
        return opcion;
    }
//    
//    
    public void setDatosConfiguracion(){        
        Vector datos = ManejadorBD.getConfiguracion();
       
        System.out.println(datos.size());
        if(!datos.isEmpty()){
            Entrada.setText(datos.get(0).toString()); 
            Procesado.setText(datos.get(1).toString());
            Log.setText(datos.get(2).toString());
            Servidor.setText(datos.get(3).toString());
            Puerto.setText(datos.get(4).toString());
            Usuario.setText(datos.get(5).toString());           

            String desencrypted = null;
            DesEncrypter encrypter = new DesEncrypter("ertg-yguy-4446-hjk756-hjfg54-fttu9-d4fc");
            if(datos.get(6)!=null){
                desencrypted = encrypter.decrypt(datos.get(6).toString());
                Contrasena.setText(desencrypted);
            }
        }
    }
    
  

    
}
