/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Licenciamiento.java
 *
 * Created on 20/06/2013, 02:52:47 PM
 */
package sconnectmail;

import BD.ManejadorBD;
import Objetos.Licencia;
import com.sun.org.apache.xerces.internal.parsers.IntegratedParserConfiguration;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.StringTokenizer;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.openswing.swing.client.OptionPane;

/**
 *
 * @author pbcgcp
 */
public class Licenciamiento extends javax.swing.JFrame {

    /** Creates new form Licenciamiento */
    public Licenciamiento() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Explorador = new javax.swing.JFrame();
        FileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        CargarLicencia = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ArchivoLicencia = new javax.swing.JTextField();
        ExaminarLog = new javax.swing.JButton();

        Explorador.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sconnectmail.SconnectMailApp.class).getContext().getResourceMap(Licenciamiento.class);
        Explorador.setTitle(resourceMap.getString("Explorador.title")); // NOI18N
        Explorador.setName("Explorador"); // NOI18N

        FileChooser.setDialogTitle(resourceMap.getString("FileChooser.dialogTitle")); // NOI18N
        FileChooser.setName("FileChooser"); // NOI18N

        javax.swing.GroupLayout ExploradorLayout = new javax.swing.GroupLayout(Explorador.getContentPane());
        Explorador.getContentPane().setLayout(ExploradorLayout);
        ExploradorLayout.setHorizontalGroup(
            ExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
            .addGroup(ExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExploradorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ExploradorLayout.setVerticalGroup(
            ExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
            .addGroup(ExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExploradorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(413, 137));
        setName("Form"); // NOI18N
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("jPanel1.border.border.lineColor")), resourceMap.getString("jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel1.border.titleFont"), resourceMap.getColor("jPanel1.border.titleColor"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        CargarLicencia.setText(resourceMap.getString("CargarLicencia.text")); // NOI18N
        CargarLicencia.setName("CargarLicencia"); // NOI18N
        CargarLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarLicenciaActionPerformed(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        ArchivoLicencia.setMaximumSize(new java.awt.Dimension(200, 20));
        ArchivoLicencia.setMinimumSize(new java.awt.Dimension(200, 20));
        ArchivoLicencia.setName("ArchivoLicencia"); // NOI18N
        ArchivoLicencia.setPreferredSize(new java.awt.Dimension(200, 20));

        ExaminarLog.setIcon(resourceMap.getIcon("ExaminarLog.icon")); // NOI18N
        ExaminarLog.setName("ExaminarLog"); // NOI18N
        ExaminarLog.setPreferredSize(new java.awt.Dimension(20, 20));
        ExaminarLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExaminarLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ArchivoLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExaminarLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(CargarLicencia)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExaminarLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ArchivoLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(CargarLicencia)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarLicenciaActionPerformed
              
        String linea;
        String firma = "";
        String salt = "";
        String fechaExpiracion = "";
        String bic = "";
        String stringTotal = "";
        StringTokenizer tok;
             
        try {
            File file = new File(ArchivoLicencia.getText());
            FileReader reader = new FileReader(file);
            BufferedReader in = new BufferedReader(reader);

            while((linea = in.readLine()) != null){
                if(linea.contains("BIC")){
                    tok = new StringTokenizer(linea,">");
                    tok.nextToken();
                    tok = new StringTokenizer(tok.nextToken(),"<");
                    bic = tok.nextToken();
                    stringTotal = stringTotal + bic;
                }       
                else if(linea.contains("FechaExpiracion")){
                    tok = new StringTokenizer(linea,">");
                    tok.nextToken();
                    tok = new StringTokenizer(tok.nextToken(),"<");
                    fechaExpiracion = tok.nextToken();
                    stringTotal = stringTotal + fechaExpiracion;
                }
                else if(linea.contains("*")){
                    salt = linea.substring(1,linea.length());             
                }
                else if(linea.contains("$")){
                    firma = linea.substring(1,linea.length());
                }
            }
            
            Licencia licencia = new Licencia();
              
            licencia.setBic(bic);     
            licencia.setFechaVencimiento(formatoFecha(fechaExpiracion));
            licencia.setSalt(salt);
            licencia.setHash(firma);
            
            ManejadorBD.setLicencia(licencia);                     
            OptionPane.showMessageDialog(null,"La licencia fue cargada con éxito","Aviso",JOptionPane.INFORMATION_MESSAGE);
            setVisible(false); 
                        
        } catch (IOException e) {
            
        }
    }//GEN-LAST:event_CargarLicenciaActionPerformed

    private void ExaminarLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExaminarLogActionPerformed
        FileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int returnVal = FileChooser.showSaveDialog(Licenciamiento.this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            ArchivoLicencia.setText(FileChooser.getSelectedFile().toString());                
        }         

        Explorador.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_ExaminarLogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Licenciamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Licenciamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Licenciamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Licenciamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Licenciamiento().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ArchivoLicencia;
    private javax.swing.JButton CargarLicencia;
    private javax.swing.JButton ExaminarLog;
    private javax.swing.JFrame Explorador;
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
   
    public static Date formatoFecha(String info){

            Date fecha = new Date();
            
            fecha.setDate(Integer.parseInt(info.substring(0,2)));
            fecha.setMonth(Integer.parseInt(info.substring(3,5))-1);            
            fecha.setYear(Integer.parseInt(info.substring(6,10))-1900);

            return fecha;

     }
    
}
