/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Licenciamiento.java
 *
 * Created on 20/06/2013, 02:52:47 PM
 */
package sconnectmail;

import BD.ManejadorBD;
import Objetos.Configuracion;
import javax.swing.JOptionPane;
import org.openswing.swing.client.OptionPane;




/**
 *
 * @author pbcgcp
 */
public class PlantillaCorreo extends javax.swing.JFrame {

    /** Creates new form Licenciamiento */
    public PlantillaCorreo() {
        initComponents();
        mostrarPlantilla();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Explorador = new javax.swing.JFrame();
        FileChooser = new javax.swing.JFileChooser();
        PanelInput = new javax.swing.JPanel();
        EncabezadoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FirmaOutput = new javax.swing.JTextArea();
        AsuntoLabel = new javax.swing.JLabel();
        AsuntoOutput = new javax.swing.JTextField();
        FirmaLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        EncabezadoOutput = new javax.swing.JTextArea();
        DefaultPlantilla = new javax.swing.JButton();
        AceptarPlantilla = new javax.swing.JButton();
        PanelInput1 = new javax.swing.JPanel();
        EncabezadoLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        FirmaInput = new javax.swing.JTextArea();
        AsuntoLabel1 = new javax.swing.JLabel();
        AsuntoInput = new javax.swing.JTextField();
        FirmaLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        EncabezadoInput = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();

        Explorador.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sconnectmail.SconnectMailApp.class).getContext().getResourceMap(PlantillaCorreo.class);
        Explorador.setTitle(resourceMap.getString("Explorador.title")); // NOI18N
        Explorador.setName("Explorador"); // NOI18N

        FileChooser.setDialogTitle(resourceMap.getString("FileChooser.dialogTitle")); // NOI18N
        FileChooser.setName("FileChooser"); // NOI18N

        javax.swing.GroupLayout ExploradorLayout = new javax.swing.GroupLayout(Explorador.getContentPane());
        Explorador.getContentPane().setLayout(ExploradorLayout);
        ExploradorLayout.setHorizontalGroup(
            ExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
            .addGroup(ExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExploradorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ExploradorLayout.setVerticalGroup(
            ExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
            .addGroup(ExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExploradorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(570, 649));
        setName("Form"); // NOI18N
        setResizable(false);

        PanelInput.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("PanelInput.border.border.lineColor")), resourceMap.getString("PanelInput.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("PanelInput.border.titleFont"), resourceMap.getColor("PanelInput.border.titleColor"))); // NOI18N
        PanelInput.setMaximumSize(new java.awt.Dimension(530, 312));
        PanelInput.setMinimumSize(new java.awt.Dimension(530, 312));
        PanelInput.setName("PanelInput"); // NOI18N
        PanelInput.setPreferredSize(new java.awt.Dimension(530, 312));

        EncabezadoLabel.setText(resourceMap.getString("EncabezadoLabel.text")); // NOI18N
        EncabezadoLabel.setName("EncabezadoLabel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        FirmaOutput.setColumns(20);
        FirmaOutput.setLineWrap(true);
        FirmaOutput.setRows(5);
        FirmaOutput.setMaximumSize(new java.awt.Dimension(164, 94));
        FirmaOutput.setMinimumSize(new java.awt.Dimension(164, 94));
        FirmaOutput.setName("FirmaOutput"); // NOI18N
        jScrollPane1.setViewportView(FirmaOutput);

        AsuntoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AsuntoLabel.setText(resourceMap.getString("AsuntoLabel.text")); // NOI18N
        AsuntoLabel.setName("AsuntoLabel"); // NOI18N

        AsuntoOutput.setText(resourceMap.getString("AsuntoOutput.text")); // NOI18N
        AsuntoOutput.setName("AsuntoOutput"); // NOI18N

        FirmaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FirmaLabel.setText(resourceMap.getString("FirmaLabel.text")); // NOI18N
        FirmaLabel.setName("FirmaLabel"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        EncabezadoOutput.setColumns(20);
        EncabezadoOutput.setLineWrap(true);
        EncabezadoOutput.setRows(5);
        EncabezadoOutput.setMaximumSize(new java.awt.Dimension(164, 94));
        EncabezadoOutput.setMinimumSize(new java.awt.Dimension(164, 94));
        EncabezadoOutput.setName("EncabezadoOutput"); // NOI18N
        jScrollPane2.setViewportView(EncabezadoOutput);

        javax.swing.GroupLayout PanelInputLayout = new javax.swing.GroupLayout(PanelInput);
        PanelInput.setLayout(PanelInputLayout);
        PanelInputLayout.setHorizontalGroup(
            PanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(FirmaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AsuntoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EncabezadoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addComponent(AsuntoOutput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelInputLayout.setVerticalGroup(
            PanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AsuntoLabel)
                    .addComponent(AsuntoOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelInputLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(EncabezadoLabel)
                        .addGap(82, 82, 82)
                        .addComponent(FirmaLabel)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInputLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );

        DefaultPlantilla.setText(resourceMap.getString("DefaultPlantilla.text")); // NOI18N
        DefaultPlantilla.setName("DefaultPlantilla"); // NOI18N
        DefaultPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefaultPlantillaActionPerformed(evt);
            }
        });

        AceptarPlantilla.setText(resourceMap.getString("AceptarPlantilla.text")); // NOI18N
        AceptarPlantilla.setName("AceptarPlantilla"); // NOI18N
        AceptarPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarPlantillaActionPerformed(evt);
            }
        });

        PanelInput1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("PanelInput1.border.border.lineColor")), resourceMap.getString("PanelInput1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("PanelInput1.border.titleFont"))); // NOI18N
        PanelInput1.setMaximumSize(new java.awt.Dimension(530, 312));
        PanelInput1.setMinimumSize(new java.awt.Dimension(530, 312));
        PanelInput1.setName("PanelInput1"); // NOI18N

        EncabezadoLabel1.setText(resourceMap.getString("EncabezadoLabel1.text")); // NOI18N
        EncabezadoLabel1.setName("EncabezadoLabel1"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        FirmaInput.setColumns(20);
        FirmaInput.setLineWrap(true);
        FirmaInput.setRows(5);
        FirmaInput.setMaximumSize(new java.awt.Dimension(164, 94));
        FirmaInput.setMinimumSize(new java.awt.Dimension(164, 94));
        FirmaInput.setName("FirmaInput"); // NOI18N
        jScrollPane3.setViewportView(FirmaInput);

        AsuntoLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AsuntoLabel1.setText(resourceMap.getString("AsuntoLabel1.text")); // NOI18N
        AsuntoLabel1.setName("AsuntoLabel1"); // NOI18N

        AsuntoInput.setName("AsuntoInput"); // NOI18N

        FirmaLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FirmaLabel1.setText(resourceMap.getString("FirmaLabel1.text")); // NOI18N
        FirmaLabel1.setName("FirmaLabel1"); // NOI18N

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        EncabezadoInput.setColumns(20);
        EncabezadoInput.setLineWrap(true);
        EncabezadoInput.setRows(5);
        EncabezadoInput.setMaximumSize(new java.awt.Dimension(164, 94));
        EncabezadoInput.setMinimumSize(new java.awt.Dimension(164, 94));
        EncabezadoInput.setName("EncabezadoInput"); // NOI18N
        jScrollPane4.setViewportView(EncabezadoInput);

        javax.swing.GroupLayout PanelInput1Layout = new javax.swing.GroupLayout(PanelInput1);
        PanelInput1.setLayout(PanelInput1Layout);
        PanelInput1Layout.setHorizontalGroup(
            PanelInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInput1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FirmaLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(EncabezadoLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AsuntoLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addComponent(AsuntoInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelInput1Layout.setVerticalGroup(
            PanelInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInput1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AsuntoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AsuntoLabel1))
                .addGroup(PanelInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelInput1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(EncabezadoLabel1)
                        .addGap(82, 82, 82)
                        .addComponent(FirmaLabel1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInput1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );

        jSeparator1.setName("jSeparator1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(DefaultPlantilla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 412, Short.MAX_VALUE)
                        .addComponent(AceptarPlantilla))
                    .addComponent(PanelInput, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelInput1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AceptarPlantilla)
                    .addComponent(DefaultPlantilla))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(PanelInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(354, Short.MAX_VALUE)))
        );

        PanelInput.getAccessibleContext().setAccessibleName(resourceMap.getString("jPanel1.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DefaultPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefaultPlantillaActionPerformed
        
        limpiarPlantilla();
        
        AsuntoInput.setText("Notificación de Transferencia - Referencia ");
        EncabezadoInput.setText("<p>Estimado(a) cliente(a),</p><p>Por este medio nos permitimos confirmar su transferencia,</p>");
        FirmaInput.setText("<br/></p><p><i>Este es un mensaje enviado autom&aacute;ticamente. Por favor no responder.<br/>Si tiene alguna inquietud con respecto a la transferencia, por favor contacte a su oficial de cuenta o ac&eacute;rquese a cualquiera de nuestras oficinas.</i></p></body></html>");
        AsuntoOutput.setText("Notificación de Transferencia - Referencia ");
        EncabezadoOutput.setText("<p>Estimado(a) cliente(a),</p><p>Por este medio nos permitimos confirmar la recepci&oacute;n de una transferencia a su cuenta,</p>");
        FirmaOutput.setText("<br/></p><p><i>Este es un mensaje enviado autom&aacute;ticamente. Por favor no responder.<br/>Si tiene alguna inquietud con respecto a la transferencia, por favor contacte a su oficial de cuenta o ac&eacute;rquese a cualquiera de nuestras oficinas.</i></p></body></html>");
      
    }//GEN-LAST:event_DefaultPlantillaActionPerformed

private void AceptarPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarPlantillaActionPerformed
        Configuracion conf = new Configuracion();
        
        conf.setPlantillaInputAsunto(AsuntoInput.getText());
        conf.setPlantillaInputEncabezado(EncabezadoInput.getText());
        conf.setPlantillaInputFirma(FirmaInput.getText());
        conf.setPlantillaOutputAsunto(AsuntoOutput.getText());
        conf.setPlantillaOutputEncabezado(EncabezadoOutput.getText());
        conf.setPlantillaOutputFirma(FirmaOutput.getText());
        
        if(ManejadorBD.setPlantilla(conf)){OptionPane.showMessageDialog(null,"Se ha actualizado la plantilla","Información",JOptionPane.INFORMATION_MESSAGE); setVisible(false);}       
}//GEN-LAST:event_AceptarPlantillaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlantillaCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlantillaCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlantillaCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlantillaCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PlantillaCorreo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarPlantilla;
    private javax.swing.JTextField AsuntoInput;
    private javax.swing.JLabel AsuntoLabel;
    private javax.swing.JLabel AsuntoLabel1;
    private javax.swing.JTextField AsuntoOutput;
    private javax.swing.JButton DefaultPlantilla;
    private javax.swing.JTextArea EncabezadoInput;
    private javax.swing.JLabel EncabezadoLabel;
    private javax.swing.JLabel EncabezadoLabel1;
    private javax.swing.JTextArea EncabezadoOutput;
    private javax.swing.JFrame Explorador;
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JTextArea FirmaInput;
    private javax.swing.JLabel FirmaLabel;
    private javax.swing.JLabel FirmaLabel1;
    private javax.swing.JTextArea FirmaOutput;
    private javax.swing.JPanel PanelInput;
    private javax.swing.JPanel PanelInput1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private void mostrarPlantilla() {
        Configuracion conf = ManejadorBD.getConfiguracion1();
        
        AsuntoInput.setText(conf.getPlantillaInputAsunto());
        EncabezadoInput.setText(conf.getPlantillaInputEncabezado());
        FirmaInput.setText(conf.getPlantillaInputFirma());
        AsuntoOutput.setText(conf.getPlantillaOutputAsunto());
        EncabezadoOutput.setText(conf.getPlantillaOutputEncabezado());
        FirmaOutput.setText(conf.getPlantillaOutputFirma());
    }
    
    private void limpiarPlantilla(){
        AsuntoInput.setText("");
        EncabezadoInput.setText("");
        FirmaInput.setText("");
        AsuntoOutput.setText("");
        EncabezadoOutput.setText("");
        FirmaOutput.setText("");
    }
   
   
    
}
