/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Reglas.java
 *
 * Created on 14/05/2013, 10:04:14 AM
 */
package sconnectmail;

import BD.ManejadorBD;
import BD.ValidarEmail;
import Objetos.Regla;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.openswing.swing.client.OptionPane;

/**
 *
 * @author pbcgcp
 */
public class Reglas extends javax.swing.JPanel {

    /** Creates new form Reglas */
    public Reglas() {
        
        initComponents();
        
        PanelDetallesRegla.setVisible(true);
        PanelAgregarRegla.setVisible(false);
        listarReglas();
        
        try{
            ReglasTable.setRowSelectionInterval(0,0);
            mostrarRegla(ReglasTable.getSelectedRow());        
        }catch(Exception e){} 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TablaReglas = new javax.swing.JPanel();
        TituloReglas = new javax.swing.JLabel();
        ContenedorReglas = new javax.swing.JScrollPane();
        ReglasTable = new javax.swing.JTable(modelo);
        AgregarRegla = new javax.swing.JButton();
        EliminarRegla = new javax.swing.JButton();
        EventosReglas = new javax.swing.JPanel();
        ContenedorEventosReglas = new javax.swing.JLayeredPane();
        PanelDetallesRegla = new javax.swing.JPanel();
        TituloDetalleAlerta = new javax.swing.JLabel();
        CancelarEditarAlerta = new javax.swing.JButton();
        EditaAlerta = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        IOReglaD = new javax.swing.JLabel();
        IOComboBoxDetalle = new javax.swing.JComboBox();
        MTReglaD = new javax.swing.JLabel();
        MTDetalle = new javax.swing.JFormattedTextField();
        MontoReglaD = new javax.swing.JLabel();
        MontoDetalle = new javax.swing.JFormattedTextField();
        MonedaReglaD = new javax.swing.JLabel();
        MonedaDetalle = new javax.swing.JFormattedTextField();
        CorreoDetalle = new javax.swing.JTextField();
        CorreoReglaD = new javax.swing.JLabel();
        CorreoClienteD = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        PanelAgregarRegla = new javax.swing.JPanel();
        TituloAgregarRegla = new javax.swing.JLabel();
        CancelarAgregarAlerta = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        IOReglaA = new javax.swing.JLabel();
        IOComboBoxAgregar = new javax.swing.JComboBox();
        MTReglaA = new javax.swing.JLabel();
        MTAgregar = new javax.swing.JFormattedTextField();
        MontoReglaA = new javax.swing.JLabel();
        MontoAgregar = new javax.swing.JFormattedTextField();
        MonedaReglaA = new javax.swing.JLabel();
        MonedaAgregar = new javax.swing.JFormattedTextField();
        CorreoAgregar = new javax.swing.JTextField();
        CorreoReglaA = new javax.swing.JLabel();
        CorreoClienteA = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        AgregarReg = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(840, 630));
        setMinimumSize(new java.awt.Dimension(840, 630));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(840, 630));

        TablaReglas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TablaReglas.setAlignmentX(0.0F);
        TablaReglas.setAlignmentY(0.0F);
        TablaReglas.setMaximumSize(new java.awt.Dimension(805, 300));
        TablaReglas.setMinimumSize(new java.awt.Dimension(805, 300));
        TablaReglas.setName("TablaReglas"); // NOI18N
        TablaReglas.setPreferredSize(new java.awt.Dimension(805, 273));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sconnectmail.SconnectMailApp.class).getContext().getResourceMap(Reglas.class);
        TituloReglas.setBackground(resourceMap.getColor("TituloReglas.background")); // NOI18N
        TituloReglas.setFont(resourceMap.getFont("TituloReglas.font")); // NOI18N
        TituloReglas.setForeground(resourceMap.getColor("TituloReglas.foreground")); // NOI18N
        TituloReglas.setText(resourceMap.getString("TituloReglas.text")); // NOI18N
        TituloReglas.setAlignmentY(0.0F);
        TituloReglas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        TituloReglas.setMaximumSize(new java.awt.Dimension(773, 28));
        TituloReglas.setMinimumSize(new java.awt.Dimension(773, 28));
        TituloReglas.setName("TituloReglas"); // NOI18N
        TituloReglas.setOpaque(true);
        TituloReglas.setPreferredSize(new java.awt.Dimension(773, 28));

        ContenedorReglas.setName("ContenedorReglas"); // NOI18N

        modelo.addColumn("Input/Output");
        modelo.addColumn("MT");
        modelo.addColumn("Monto");
        modelo.addColumn("Moneda");
        modelo.addColumn("Correo Dpto.");
        modelo.addColumn("Correo Cliente");
        modelo.addColumn("");

        ReglasTable.getColumnModel().getColumn(0).setMaxWidth(80);
        ReglasTable.getColumnModel().getColumn(0).setMinWidth(80);
        ReglasTable.getColumnModel().getColumn(1).setMaxWidth(60);
        ReglasTable.getColumnModel().getColumn(1).setMinWidth(60);
        ReglasTable.getColumnModel().getColumn(2).setMaxWidth(70);
        ReglasTable.getColumnModel().getColumn(2).setMinWidth(70);
        ReglasTable.getColumnModel().getColumn(3).setMaxWidth(70);
        ReglasTable.getColumnModel().getColumn(3).setMinWidth(70);
        ReglasTable.getColumnModel().getColumn(4).setMaxWidth(160);
        ReglasTable.getColumnModel().getColumn(4).setMinWidth(160);
        ReglasTable.getColumnModel().getColumn(5).setMaxWidth(80);
        ReglasTable.getColumnModel().getColumn(5).setMinWidth(80);
        TableColumn test = ReglasTable.getColumnModel().getColumn(5);
        test.setCellEditor(new DefaultCellEditor(new JCheckBox()));
        test.setCellRenderer(new ShadedTableCellRenderer());
        ReglasTable.getColumnModel().getColumn(6).setMaxWidth(10);
        ReglasTable.getColumnModel().getColumn(6).setMinWidth(10);

        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        ReglasTable.getColumnModel().getColumn(0).setCellRenderer(tcr);
        ReglasTable.getColumnModel().getColumn(1).setCellRenderer(tcr);
        ReglasTable.getColumnModel().getColumn(2).setCellRenderer(tcr);
        ReglasTable.getColumnModel().getColumn(3).setCellRenderer(tcr);
        ReglasTable.getColumnModel().getColumn(4).setCellRenderer(tcr);
        //ReglasTable.getColumnModel().getColumn(5).setCellRenderer(tcr);
        ReglasTable.getColumnModel().getColumn(6).setCellRenderer(tcr);
        ReglasTable.setAutoCreateRowSorter(true);
        ReglasTable.setName("ReglasTable"); // NOI18N
        try{ReglasTable.addRowSelectionInterval(0,0);}catch(Exception ex){}
        ReglasTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReglasTableMouseClicked(evt);
            }
        });
        ReglasTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ReglasTableKeyReleased(evt);
            }
        });
        ContenedorReglas.setViewportView(ReglasTable);

        AgregarRegla.setText(resourceMap.getString("AgregarRegla.text")); // NOI18N
        AgregarRegla.setAlignmentY(0.0F);
        AgregarRegla.setMaximumSize(new java.awt.Dimension(81, 23));
        AgregarRegla.setMinimumSize(new java.awt.Dimension(81, 23));
        AgregarRegla.setName("AgregarRegla"); // NOI18N
        AgregarRegla.setPreferredSize(new java.awt.Dimension(81, 23));
        AgregarRegla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarReglaMouseClicked(evt);
            }
        });

        EliminarRegla.setText(resourceMap.getString("EliminarRegla.text")); // NOI18N
        EliminarRegla.setAlignmentY(0.0F);
        EliminarRegla.setMaximumSize(new java.awt.Dimension(81, 23));
        EliminarRegla.setMinimumSize(new java.awt.Dimension(81, 23));
        EliminarRegla.setName("EliminarRegla"); // NOI18N
        EliminarRegla.setPreferredSize(new java.awt.Dimension(81, 23));
        EliminarRegla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarReglaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TablaReglasLayout = new javax.swing.GroupLayout(TablaReglas);
        TablaReglas.setLayout(TablaReglasLayout);
        TablaReglasLayout.setHorizontalGroup(
            TablaReglasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TablaReglasLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(ContenedorReglas, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(TablaReglasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AgregarRegla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarRegla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addComponent(TituloReglas, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );
        TablaReglasLayout.setVerticalGroup(
            TablaReglasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablaReglasLayout.createSequentialGroup()
                .addComponent(TituloReglas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(TablaReglasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TablaReglasLayout.createSequentialGroup()
                        .addComponent(AgregarRegla, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EliminarRegla, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ContenedorReglas, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        EventosReglas.setMaximumSize(new java.awt.Dimension(805, 290));
        EventosReglas.setMinimumSize(new java.awt.Dimension(805, 290));
        EventosReglas.setName("EventosReglas"); // NOI18N
        EventosReglas.setPreferredSize(new java.awt.Dimension(805, 290));

        ContenedorEventosReglas.setMaximumSize(new java.awt.Dimension(805, 290));
        ContenedorEventosReglas.setMinimumSize(new java.awt.Dimension(805, 290));
        ContenedorEventosReglas.setName("ContenedorEventosReglas"); // NOI18N

        PanelDetallesRegla.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelDetallesRegla.setMaximumSize(new java.awt.Dimension(805, 290));
        PanelDetallesRegla.setMinimumSize(new java.awt.Dimension(805, 290));
        PanelDetallesRegla.setName("PanelDetallesRegla"); // NOI18N
        PanelDetallesRegla.setPreferredSize(new java.awt.Dimension(805, 290));
        PanelDetallesRegla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloDetalleAlerta.setBackground(resourceMap.getColor("TituloDetalleAlerta.background")); // NOI18N
        TituloDetalleAlerta.setFont(resourceMap.getFont("TituloDetalleAlerta.font")); // NOI18N
        TituloDetalleAlerta.setForeground(resourceMap.getColor("TituloDetalleAlerta.foreground")); // NOI18N
        TituloDetalleAlerta.setText(resourceMap.getString("TituloDetalleAlerta.text")); // NOI18N
        TituloDetalleAlerta.setAlignmentY(0.0F);
        TituloDetalleAlerta.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        TituloDetalleAlerta.setMaximumSize(new java.awt.Dimension(801, 28));
        TituloDetalleAlerta.setMinimumSize(new java.awt.Dimension(801, 28));
        TituloDetalleAlerta.setName("TituloDetalleAlerta"); // NOI18N
        TituloDetalleAlerta.setOpaque(true);
        TituloDetalleAlerta.setPreferredSize(new java.awt.Dimension(801, 28));
        PanelDetallesRegla.add(TituloDetalleAlerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, -1));

        CancelarEditarAlerta.setText(resourceMap.getString("CancelarEditarAlerta.text")); // NOI18N
        CancelarEditarAlerta.setMaximumSize(new java.awt.Dimension(81, 23));
        CancelarEditarAlerta.setMinimumSize(new java.awt.Dimension(81, 23));
        CancelarEditarAlerta.setName("CancelarEditarAlerta"); // NOI18N
        CancelarEditarAlerta.setPreferredSize(new java.awt.Dimension(81, 23));
        CancelarEditarAlerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarEditarAlertaActionPerformed(evt);
            }
        });
        PanelDetallesRegla.add(CancelarEditarAlerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, -1, -1));

        EditaAlerta.setText(resourceMap.getString("EditaAlerta.text")); // NOI18N
        EditaAlerta.setMaximumSize(new java.awt.Dimension(81, 23));
        EditaAlerta.setMinimumSize(new java.awt.Dimension(81, 23));
        EditaAlerta.setName("EditaAlerta"); // NOI18N
        EditaAlerta.setPreferredSize(new java.awt.Dimension(81, 23));
        EditaAlerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditaAlertaActionPerformed(evt);
            }
        });
        PanelDetallesRegla.add(EditaAlerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setName("jPanel4"); // NOI18N

        IOReglaD.setText(resourceMap.getString("IOReglaD.text")); // NOI18N
        IOReglaD.setName("IOReglaD"); // NOI18N

        IOComboBoxDetalle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar...", "INPUT", "OUTPUT" }));
        IOComboBoxDetalle.setName("IOComboBoxDetalle"); // NOI18N

        MTReglaD.setText(resourceMap.getString("MTReglaD.text")); // NOI18N
        MTReglaD.setName("MTReglaD"); // NOI18N

        MTDetalle.setName("MTDetalle"); // NOI18N

        MontoReglaD.setText(resourceMap.getString("MontoReglaD.text")); // NOI18N
        MontoReglaD.setName("MontoReglaD"); // NOI18N

        MontoDetalle.setName("MontoDetalle"); // NOI18N

        MonedaReglaD.setText(resourceMap.getString("MonedaReglaD.text")); // NOI18N
        MonedaReglaD.setName("MonedaReglaD"); // NOI18N

        MonedaDetalle.setName("MonedaDetalle"); // NOI18N

        CorreoDetalle.setName("CorreoDetalle"); // NOI18N

        CorreoReglaD.setText(resourceMap.getString("CorreoReglaD.text")); // NOI18N
        CorreoReglaD.setName("CorreoReglaD"); // NOI18N

        CorreoClienteD.setText(resourceMap.getString("CorreoClienteD.text")); // NOI18N
        CorreoClienteD.setName("CorreoClienteD"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MontoReglaD)
                    .addComponent(MonedaReglaD)
                    .addComponent(MTReglaD)
                    .addComponent(IOReglaD))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MonedaDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MTDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IOComboBoxDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MontoDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(CorreoReglaD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(CorreoDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5))
                            .addComponent(CorreoClienteD, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IOReglaD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IOComboBoxDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MTDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MTReglaD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CorreoReglaD)
                            .addComponent(CorreoDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MontoDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MontoReglaD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MonedaReglaD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MonedaDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(CorreoClienteD))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        PanelDetallesRegla.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 780, 190));

        PanelDetallesRegla.setBounds(0, 0, 805, 290);
        ContenedorEventosReglas.add(PanelDetallesRegla, javax.swing.JLayeredPane.DEFAULT_LAYER);

        PanelAgregarRegla.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelAgregarRegla.setMaximumSize(new java.awt.Dimension(805, 290));
        PanelAgregarRegla.setMinimumSize(new java.awt.Dimension(805, 290));
        PanelAgregarRegla.setName("PanelAgregarRegla"); // NOI18N
        PanelAgregarRegla.setPreferredSize(new java.awt.Dimension(805, 290));
        PanelAgregarRegla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloAgregarRegla.setBackground(resourceMap.getColor("TituloAgregarRegla.background")); // NOI18N
        TituloAgregarRegla.setFont(resourceMap.getFont("TituloAgregarRegla.font")); // NOI18N
        TituloAgregarRegla.setForeground(resourceMap.getColor("TituloAgregarRegla.foreground")); // NOI18N
        TituloAgregarRegla.setText(resourceMap.getString("TituloAgregarRegla.text")); // NOI18N
        TituloAgregarRegla.setAlignmentY(0.0F);
        TituloAgregarRegla.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        TituloAgregarRegla.setMaximumSize(new java.awt.Dimension(801, 28));
        TituloAgregarRegla.setMinimumSize(new java.awt.Dimension(801, 28));
        TituloAgregarRegla.setName("TituloAgregarRegla"); // NOI18N
        TituloAgregarRegla.setOpaque(true);
        TituloAgregarRegla.setPreferredSize(new java.awt.Dimension(801, 28));
        PanelAgregarRegla.add(TituloAgregarRegla, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, -1));

        CancelarAgregarAlerta.setText(resourceMap.getString("CancelarAgregarAlerta.text")); // NOI18N
        CancelarAgregarAlerta.setMaximumSize(new java.awt.Dimension(81, 23));
        CancelarAgregarAlerta.setMinimumSize(new java.awt.Dimension(81, 23));
        CancelarAgregarAlerta.setName("CancelarAgregarAlerta"); // NOI18N
        CancelarAgregarAlerta.setPreferredSize(new java.awt.Dimension(81, 23));
        CancelarAgregarAlerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarAgregarAlertaActionPerformed(evt);
            }
        });
        PanelAgregarRegla.add(CancelarAgregarAlerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setName("jPanel3"); // NOI18N

        IOReglaA.setText(resourceMap.getString("IOReglaA.text")); // NOI18N
        IOReglaA.setName("IOReglaA"); // NOI18N

        IOComboBoxAgregar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar...", "INPUT", "OUTPUT" }));
        IOComboBoxAgregar.setName("IOComboBoxAgregar"); // NOI18N

        MTReglaA.setText(resourceMap.getString("MTReglaA.text")); // NOI18N
        MTReglaA.setName("MTReglaA"); // NOI18N

        MTAgregar.setName("MTAgregar"); // NOI18N

        MontoReglaA.setText(resourceMap.getString("MontoReglaA.text")); // NOI18N
        MontoReglaA.setName("MontoReglaA"); // NOI18N

        MontoAgregar.setName("MontoAgregar"); // NOI18N

        MonedaReglaA.setText(resourceMap.getString("MonedaReglaA.text")); // NOI18N
        MonedaReglaA.setName("MonedaReglaA"); // NOI18N

        MonedaAgregar.setName("MonedaAgregar"); // NOI18N

        CorreoAgregar.setName("CorreoAgregar"); // NOI18N

        CorreoReglaA.setText(resourceMap.getString("CorreoReglaA.text")); // NOI18N
        CorreoReglaA.setName("CorreoReglaA"); // NOI18N

        CorreoClienteA.setText(resourceMap.getString("CorreoClienteA.text")); // NOI18N
        CorreoClienteA.setName("CorreoClienteA"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MontoReglaA)
                    .addComponent(MonedaReglaA)
                    .addComponent(IOReglaA)
                    .addComponent(MTReglaA))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MonedaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MontoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IOComboBoxAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MTAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CorreoClienteA, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(CorreoReglaA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CorreoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IOReglaA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IOComboBoxAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CorreoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CorreoReglaA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MTReglaA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MTAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MontoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MontoReglaA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MonedaReglaA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MonedaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(CorreoClienteA)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        PanelAgregarRegla.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 780, 190));

        AgregarReg.setText(resourceMap.getString("AgregarReg.text")); // NOI18N
        AgregarReg.setMaximumSize(new java.awt.Dimension(81, 23));
        AgregarReg.setMinimumSize(new java.awt.Dimension(81, 23));
        AgregarReg.setName("AgregarReg"); // NOI18N
        AgregarReg.setPreferredSize(new java.awt.Dimension(81, 23));
        AgregarReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarRegActionPerformed(evt);
            }
        });
        PanelAgregarRegla.add(AgregarReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, -1));

        PanelAgregarRegla.setBounds(0, 0, 805, 290);
        ContenedorEventosReglas.add(PanelAgregarRegla, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EventosReglasLayout = new javax.swing.GroupLayout(EventosReglas);
        EventosReglas.setLayout(EventosReglasLayout);
        EventosReglasLayout.setHorizontalGroup(
            EventosReglasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 805, Short.MAX_VALUE)
            .addGroup(EventosReglasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ContenedorEventosReglas, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        EventosReglasLayout.setVerticalGroup(
            EventosReglasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(EventosReglasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ContenedorEventosReglas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TablaReglas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EventosReglas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TablaReglas, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EventosReglas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(331, 331, 331))
        );
    }// </editor-fold>//GEN-END:initComponents

private void ReglasTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReglasTableMouseClicked
    resetCamposDe();
    mostrarRegla(ReglasTable.getSelectedRow());
}//GEN-LAST:event_ReglasTableMouseClicked

private void ReglasTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ReglasTableKeyReleased
    resetCamposDe();    
    mostrarRegla(ReglasTable.getSelectedRow());
}//GEN-LAST:event_ReglasTableKeyReleased

private void AgregarReglaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarReglaMouseClicked
    PanelAgregarRegla.setVisible(true);    
    PanelDetallesRegla.setVisible(false);
}//GEN-LAST:event_AgregarReglaMouseClicked

private void EliminarReglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarReglaActionPerformed
        int opcion = OptionPane.showConfirmDialog(null,"¿Está seguro que desea eliminar el registro?","Advertencia",JOptionPane.YES_NO_OPTION);  //0 Aceptar

        if(opcion == 0){

            Long idRegla = (Long) ReglasTable.getValueAt(ReglasTable.getSelectedRow(),6);
     
            if(ManejadorBD.deleteRegla(idRegla)){
                OptionPane.showMessageDialog(null,"Se ha eliminado el registro","Información",JOptionPane.INFORMATION_MESSAGE);
            } else{
                OptionPane.showMessageDialog(null,"Ha ocurrido un error eliminando el registro","Error",JOptionPane.ERROR_MESSAGE);
            }
        }

        listarReglas();
        mostrarRegla(0);
}//GEN-LAST:event_EliminarReglaActionPerformed

private void CancelarEditarAlertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarEditarAlertaActionPerformed
       
}//GEN-LAST:event_CancelarEditarAlertaActionPerformed

private void EditaAlertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditaAlertaActionPerformed

        int opcion = OptionPane.showConfirmDialog(null,"¿Está seguro que desea modificar el registro?","Advertencia",JOptionPane.YES_NO_OPTION);  //0 Aceptar

        if (opcion == 0){       
       
            Regla regla = new Regla();    
            
            regla.setId((Long)ReglasTable.getValueAt(ReglasTable.getSelectedRow(),6));
       
            if(IOComboBoxDetalle.getSelectedItem().toString().equals("INPUT")){regla.setIo("I");}
            else if(IOComboBoxDetalle.getSelectedItem().toString().equals("OUTPUT")){regla.setIo("O");}  
    
            if(CorreoClienteD.isSelected()){regla.setMailToCliente('S');}else{regla.setMailToCliente('N');}
            if(!CorreoDetalle.getText().isEmpty()){regla.setMailToDpto(CorreoDetalle.getText());}
            if(!MonedaDetalle.getText().isEmpty()){regla.setMoneda(MonedaDetalle.getText());}
            if(!MontoDetalle.getText().isEmpty()){regla.setMonto(Double.parseDouble(MontoDetalle.getText()));}
            if(!MTDetalle.getText().isEmpty()){regla.setMt(Integer.parseInt(MTDetalle.getText()));}
           
            if(CorreoDetalle.getText().isEmpty()){OptionPane.showMessageDialog(null,"Debe colocar un correo válido","Error",JOptionPane.ERROR_MESSAGE); }
             else{
                ManejadorBD.updateRegla(regla);
                listarReglas();
            }       
        }
}//GEN-LAST:event_EditaAlertaActionPerformed

private void CancelarAgregarAlertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarAgregarAlertaActionPerformed
    resetCamposAg();    
    PanelAgregarRegla.setVisible(false);
    PanelDetallesRegla.setVisible(true);    
}//GEN-LAST:event_CancelarAgregarAlertaActionPerformed

private void AgregarRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarRegActionPerformed
    Regla regla = new Regla();
    
    if(IOComboBoxAgregar.getSelectedItem().toString().equals("INPUT")){regla.setIo("I");}
    else if(IOComboBoxAgregar.getSelectedItem().toString().equals("OUTPUT")){regla.setIo("O");}  
    
    if(CorreoClienteA.isSelected()){regla.setMailToCliente('S');}else{regla.setMailToCliente('N');}
    if(!CorreoAgregar.getText().isEmpty()){regla.setMailToDpto(CorreoAgregar.getText());}
    if(!MonedaAgregar.getText().isEmpty()){regla.setMoneda(MonedaAgregar.getText());}
    if(!MontoAgregar.getText().isEmpty()){regla.setMonto(Double.parseDouble(MontoAgregar.getText()));}
    if(!MTAgregar.getText().isEmpty()){regla.setMt(Integer.parseInt(MTAgregar.getText()));}
           
    if(CorreoAgregar.getText().isEmpty()){OptionPane.showMessageDialog(null,"Debe colocar un correo válido","Error",JOptionPane.ERROR_MESSAGE); }
     else{
        boolean resultado = ManejadorBD.setRegla(regla);
        
        if(resultado){
            resetCamposAg();
            PanelDetallesRegla.setVisible(true);
            PanelAgregarRegla.setVisible(false);

            listarReglas();
        }
    }       
    
}//GEN-LAST:event_AgregarRegActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarReg;
    private javax.swing.JButton AgregarRegla;
    private javax.swing.JButton CancelarAgregarAlerta;
    private javax.swing.JButton CancelarEditarAlerta;
    private javax.swing.JLayeredPane ContenedorEventosReglas;
    private javax.swing.JScrollPane ContenedorReglas;
    private javax.swing.JTextField CorreoAgregar;
    private javax.swing.JCheckBox CorreoClienteA;
    private javax.swing.JCheckBox CorreoClienteD;
    private javax.swing.JTextField CorreoDetalle;
    private javax.swing.JLabel CorreoReglaA;
    private javax.swing.JLabel CorreoReglaD;
    private javax.swing.JButton EditaAlerta;
    private javax.swing.JButton EliminarRegla;
    private javax.swing.JPanel EventosReglas;
    private javax.swing.JComboBox IOComboBoxAgregar;
    private javax.swing.JComboBox IOComboBoxDetalle;
    private javax.swing.JLabel IOReglaA;
    private javax.swing.JLabel IOReglaD;
    private javax.swing.JFormattedTextField MTAgregar;
    private javax.swing.JFormattedTextField MTDetalle;
    private javax.swing.JLabel MTReglaA;
    private javax.swing.JLabel MTReglaD;
    private javax.swing.JFormattedTextField MonedaAgregar;
    private javax.swing.JFormattedTextField MonedaDetalle;
    private javax.swing.JLabel MonedaReglaA;
    private javax.swing.JLabel MonedaReglaD;
    private javax.swing.JFormattedTextField MontoAgregar;
    private javax.swing.JFormattedTextField MontoDetalle;
    private javax.swing.JLabel MontoReglaA;
    private javax.swing.JLabel MontoReglaD;
    private javax.swing.JPanel PanelAgregarRegla;
    private javax.swing.JPanel PanelDetallesRegla;
    private javax.swing.JTable ReglasTable;
    private javax.swing.JPanel TablaReglas;
    private javax.swing.JLabel TituloAgregarRegla;
    private javax.swing.JLabel TituloDetalleAlerta;
    private javax.swing.JLabel TituloReglas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    DefaultTableModel modelo = new DefaultTableModel();
    
    public void mostrarRegla(int fila){
        
        if(ReglasTable.getRowCount() != 0){            
            if(ReglasTable.getValueAt(fila,0) != null ){
                if(ReglasTable.getValueAt(fila,0).equals("I")){IOComboBoxDetalle.setSelectedIndex(1);}
                else if(ReglasTable.getValueAt(fila,0).equals("O")){IOComboBoxDetalle.setSelectedIndex(2);}
                else{IOComboBoxDetalle.setSelectedIndex(0);}            
            }       
            if(ReglasTable.getValueAt(fila,1) != null ){MTDetalle.setText(ReglasTable.getValueAt(fila,1).toString());}
            if(ReglasTable.getValueAt(fila,2) != null ){MontoDetalle.setText(ReglasTable.getValueAt(fila,2).toString());}
            if(ReglasTable.getValueAt(fila,3) != null ){MonedaDetalle.setText(ReglasTable.getValueAt(fila,3).toString());}
            if(ReglasTable.getValueAt(fila,4) != null ){CorreoDetalle.setText(ReglasTable.getValueAt(fila,4).toString());}
            if(ReglasTable.getValueAt(fila,5).equals(true)){CorreoClienteD.setSelected(true);}else{CorreoClienteD.setSelected(false);}        
        }
    }

    public void listarReglas(){
        modelo.setRowCount(0);
        List reglas = ManejadorBD.getReglas();
  
        for (int i = 0; i < reglas.size(); i++) {
            Regla regla = (Regla) reglas.get(i);
            Vector aux = new Vector();
          
            aux.add(regla.getIo());
            aux.add(regla.getMt());
            aux.add(regla.getMonto());
            aux.add(regla.getMoneda());
            aux.add(regla.getMailToDpto());
            if(regla.getMailToCliente() == 'S'){aux.add(new Boolean(true));}
            else if(regla.getMailToCliente() == 'N' || regla.getMailToCliente() == null){aux.add(new Boolean(false));}
            aux.add(regla.getId());

            modelo.addRow(aux);            
        }
    }
    
    public void resetCamposAg(){
        MTAgregar.setText("");
        IOComboBoxAgregar.setSelectedIndex(0);       
        CorreoAgregar.setText("");
        MonedaAgregar.setText("");
        MontoAgregar.setText("");     
    }
    
    public void resetCamposDe(){
        MTDetalle.setText("");
        IOComboBoxDetalle.setSelectedIndex(0);       
        CorreoDetalle.setText("");
        MonedaDetalle.setText("");
        MontoDetalle.setText("");     
    }
    
     private boolean correoesValido(JTextField correo) {
        ValidarEmail emailValidator = new ValidarEmail ();
        
        if(!emailValidator.validate(correo.getText().trim())) {            
            return false;            
        }
        else{return true;}
    }

}


